base/src/main/java/io/customer/base/error/ErrorDetail.kt
base/src/main/java/io/customer/base/error/StatusCode.kt
buildSrc/src/main/kotlin/io.customer/android/Dependencies.kt
buildSrc/src/main/kotlin/io.customer/android/Versions.kt
sdk/build.gradle
sdk/src/main/java/io/customer/sdk/CustomerIo.kt
sdk/src/main/java/io/customer/sdk/CustomerIoClient.kt
sdk/src/main/java/io/customer/sdk/CustomerIoConfig.kt
sdk/src/main/java/io/customer/sdk/api/CustomerIoApi.kt
sdk/src/main/java/io/customer/sdk/api/service/CustomerService.kt
sdk/src/main/java/io/customer/sdk/data/model/IdentityAttributeValue.kt
sdk/src/main/java/io/customer/sdk/di/CustomerIoComponent.kt
sdk/src/main/java/io/customer/sdk/repository/IdentityRepository.kt

Caters #3 
- Added Identity repository
- Added APIs integration 
- Added client configuration

chore: Added ability to identity customer

---

sdk/src/main/java/io/customer/sdk/data/request/Metric.kt

https://github.com/square/moshi#r8--proguard

fix: prevent enum from being removed/obfuscated

---

app/src/main/java/io/customer/example/MainActivity.kt
sdk/src/main/java/io/customer/sdk/CustomerIO.kt
sdk/src/main/java/io/customer/sdk/CustomerIOClient.kt
sdk/src/main/java/io/customer/sdk/api/CustomerIOApi.kt
sdk/src/main/java/io/customer/sdk/api/retrofit/CustomerIoCallAdapter.kt
sdk/src/main/java/io/customer/sdk/data/model/EventType.kt
sdk/src/main/java/io/customer/sdk/data/request/Event.kt
sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
sdk/src/main/java/io/customer/sdk/repository/TrackingRepository.kt
sdk/src/test/java/io/customer/sdk/CustomerIOClientTest.kt
sdk/src/test/java/io/customer/sdk/CustomerIOTest.kt
sdk/src/test/java/io/customer/sdk/MockCustomerIOBuilder.kt
sdk/src/test/java/io/customer/sdk/api/CustomerIOCallAdapterTest.kt
sdk/src/test/java/io/customer/sdk/repositories/TrackingRepositoryTest.kt

Screen tracking has been divided into two parts
- Manual 
- Automatic 
This PR tackles the manual one.

feat: manual screen tracking

---

README.md

This is a new PR after [deleting the old one](https://github.com/customerio/customerio-android/pull/54). Same change, but fixes the git issue that I [mention](https://github.com/customerio/customerio-android/pull/54#issuecomment-1016767031)

docs: remove alpha references from README

---

.github/workflows/deploy-git-tag.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Part of [git-flow](https://nvie.com/posts/a-successful-git-branching-model/) is that once you make a production deployment, you merge those commits back into your develop branch. I forgot to add this step to https://github.com/customerio/customerio-android/pull/59. This PR adds this task in where commits added to main will be merged into develop after a production deployment.

ci: copy commits from main after deployment

---

.github/workflows/deploy-git-tag.yml
.github/workflows/lint.yml
.github/workflows/pr-helper.yml
.github/workflows/promote.yml
.github/workflows/snapshot-release.yml
.github/workflows/test.yml

ci: update bot tokens to read/write accesses

---

messagingpush/src/main/java/io/customer/messagingpush/CustomerIOFirebaseMessagingService.kt
sdk/src/main/java/io/customer/sdk/CustomerIO.kt

Adding `JvmOverloads` to instruct the Kotlin compiler to generate overloads for the functions that substitute default parameter values.

fix: added java compatibility in public constructors and methods

---

app/src/main/java/io/customer/example/MainActivity.kt
sdk/build.gradle
sdk/src/main/java/io/customer/sdk/CustomerIO.kt
sdk/src/main/java/io/customer/sdk/CustomerIOClient.kt
sdk/src/main/java/io/customer/sdk/api/CustomerIOApi.kt
sdk/src/main/java/io/customer/sdk/data/request/Device.kt
sdk/src/main/java/io/customer/sdk/data/store/ApplicationStore.kt
sdk/src/main/java/io/customer/sdk/data/store/BuildStore.kt
sdk/src/main/java/io/customer/sdk/data/store/DeviceStore.kt
sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
sdk/src/main/java/io/customer/sdk/repository/PushNotificationRepository.kt
sdk/src/test/java/io/customer/sdk/BaseTest.kt
sdk/src/test/java/io/customer/sdk/CustomerIOClientTest.kt
sdk/src/test/java/io/customer/sdk/CustomerIOTest.kt
sdk/src/test/java/io/customer/sdk/repositories/PushNotificationRepositoryTest.kt
sdk/src/test/java/io/customer/sdk/store/DeviceStoreTest.kt
sdk/src/test/java/io/customer/sdk/utils/DeviceStoreStub.kt

feat: added support for device attributes

---

CHANGELOG.md
sdk/src/main/java/io/customer/sdk/Version.kt
sdk/src/main/java/io/customer/sdk/data/store/ApplicationStore.kt
sdk/src/main/java/io/customer/sdk/data/store/DeviceStore.kt
sdk/src/test/java/io/customer/sdk/store/DeviceStoreTest.kt

Automatically syncing these 2 branches failed by the CI server. Merge this pull request manually instead.

Merge main into develop

---

.github/pull_request_template.md
.releaserc.json
CHANGELOG.md
CODE_OF_CONDUCT.md
app/src/androidTest/java/io/customer/example/ExampleInstrumentedTest.kt
app/src/main/AndroidManifest.xml
app/src/main/res/layout/activity_main.xml
app/src/test/java/io/customer/example/ExampleUnitTest.kt
app/src/test/java/io/customer/example/ExampleUnitTest2.kt
buildSrc/build.gradle.kts
docs/dev-notes/GIT-WORKFLOW.md
messagingpush/src/androidTest/java/io/customer/messagingpush/ExampleInstrumentedTest.kt
messagingpush/src/test/java/io/customer/messagingpush/ExampleUnitTest.kt
scripts/androidStudioRunConfigurations/install local.run.xml
scripts/publish-root.gradle
sdk/src/main/java/io/customer/sdk/Version.kt
sdk/src/main/java/io/customer/sdk/repository/AttributesRepository.kt

fix: code cleanup 

---

sdk/src/main/java/io/customer/sdk/data/store/DeviceStore.kt
sdk/src/test/java/io/customer/sdk/store/DeviceStoreTest.kt

Closes https://github.com/customerio/issues/issues/7128

feat: add device_manufacturer device attribute

---

.github/workflows/test.yml
README.md

Small improvement to the code coverage uploading CI step. These changes came because of errors we had with the iOS SDK so copying over fixes here to prevent the same errors from happening. 

ci: improve success of code coverage uploading

---

.github/workflows/snapshot-release.yml
sdk/src/main/java/io/customer/sdk/CustomerIOClient.kt
sdk/src/sharedTest/java/io/customer/sdk/CustomerIOClientTest.kt

Fixes: https://github.com/customerio/issues/issues/7215

fix: events are tracked to identified customer

---

common-test/src/main/java/io/customer/common_test/BaseTest.kt
sdk/src/main/java/io/customer/sdk/CustomerIO.kt
sdk/src/main/java/io/customer/sdk/CustomerIOConfig.kt
sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
sdk/src/main/java/io/customer/sdk/util/Logger.kt
sdk/src/sharedTest/java/io/customer/sdk/util/LoggerTest.kt

Closes: https://github.com/customerio/issues/issues/7295

feat: set log level via SDK config

---

common-test/build.gradle
common-test/src/main/java/io/customer/common_test/BaseTest.kt
common-test/src/main/java/io/customer/common_test/extensions/RetrofitExtensions.kt
sdk/src/debug/AndroidManifest.xml
sdk/src/debug/res/xml/allow_localhost_cleartext.xml
sdk/src/main/java/io/customer/sdk/CustomerIOClient.kt
sdk/src/main/java/io/customer/sdk/CustomerIOConfig.kt
sdk/src/main/java/io/customer/sdk/data/model/Region.kt
sdk/src/main/java/io/customer/sdk/data/request/Device.kt
sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
sdk/src/main/java/io/customer/sdk/queue/Queue.kt
sdk/src/main/java/io/customer/sdk/queue/QueueQueryRunner.kt
sdk/src/main/java/io/customer/sdk/queue/QueueRunRequest.kt
sdk/src/main/java/io/customer/sdk/util/SimpleTimer.kt
sdk/src/sharedTest/java/io/customer/sdk/CustomerIOClientTest.kt
sdk/src/sharedTest/java/io/customer/sdk/data/store/FileStorageTest.kt
sdk/src/sharedTest/java/io/customer/sdk/queue/QueueIntegrationTests.kt
sdk/src/sharedTest/java/io/customer/sdk/queue/QueueQueryRunnerTest.kt
sdk/src/sharedTest/java/io/customer/sdk/queue/QueueRunRequestTest.kt
sdk/src/sharedTest/java/io/customer/sdk/queue/QueueTest.kt

Fixes: https://github.com/customerio/issues/issues/7255

fix: queue attempts to run all tasks on each run

---

sdk/src/main/java/io/customer/sdk/CustomerIOClient.kt
sdk/src/main/java/io/customer/sdk/data/store/FileStorage.kt
sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
sdk/src/main/java/io/customer/sdk/queue/Queue.kt
sdk/src/main/java/io/customer/sdk/queue/QueueStorage.kt
sdk/src/sharedTest/java/io/customer/sdk/data/store/FileStorageTest.kt
sdk/src/sharedTest/java/io/customer/sdk/queue/QueueStorageIntegrationTest.kt

https://github.com/customerio/issues/issues/6622

refactor: improve logging when task not added to queue successfully

---

app/src/main/java/io/customer/example/MainActivity.kt
sdk/src/main/java/io/customer/sdk/CustomerIO.kt
sdk/src/main/java/io/customer/sdk/CustomerIOClient.kt
sdk/src/main/java/io/customer/sdk/api/CustomerIOApi.kt
sdk/src/sharedTest/java/io/customer/sdk/CustomerIOClientTest.kt
sdk/src/sharedTest/java/io/customer/sdk/CustomerIOTest.kt

Closes: https://github.com/customerio/issues/issues/7245

feat: add device and profile attribute setters

---

sdk/src/main/java/io/customer/sdk/repository/ProfileRepository.kt
sdk/src/sharedTest/java/io/customer/sdk/repository/ProfileRepositoryTest.kt

fix: delete device token when clear identify

---

.github/workflows/deploy-maven-central.yml
scripts/deploy-code.sh

Similar to [this PR](https://github.com/customerio/customerio-android/pull/119), create a script that makes it easier to do a manual deployment. Not having to read the CI server code. 

ci: edit code deployment for easier manual deployment

---

scripts/deploy-code.sh

fix: deploy code script commands

---

common-test/src/main/java/io/customer/commontest/BaseTest.kt
common-test/src/main/java/io/customer/commontest/DeviceStoreStub.kt
messaginginapp/src/main/java/io/customer/messaginginapp/MessagingInAppModuleConfig.kt
messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushReceiver.kt
messagingpush/src/main/java/io/customer/messagingpush/MessagingPushModuleConfig.kt
messagingpush/src/main/java/io/customer/messagingpush/ModuleMessagingPushFCM.kt
messagingpush/src/main/java/io/customer/messagingpush/lifecycle/MessagingPushLifecycleCallback.kt
messagingpush/src/sharedTest/java/io/customer/messagingpush/ModuleMessagingConfigTest.kt
messagingpush/src/sharedTest/java/io/customer/messagingpush/ModuleMessagingPushFCMTest.kt
sdk/src/main/java/io/customer/sdk/CustomerIO.kt
sdk/src/main/java/io/customer/sdk/CustomerIOConfig.kt
sdk/src/main/java/io/customer/sdk/data/store/Client.kt
sdk/src/main/java/io/customer/sdk/data/store/DeviceStore.kt
sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
sdk/src/main/java/io/customer/sdk/module/CustomerIOModuleConfig.kt

This PR adds support for the changes required to align with iOS SDK and make react native package easier to interact
To fix deep link navigation from notifications, this PR has following changes
- Exposed config in core SDK for following options
-  `backgroundQueueMinNumberOfTasks`
- `backgroundQueueSecondsDelay`
- Added config in in-app module for following options
- `autoTrackPushEvents`
- Updated module configurations to enforce builder pattern
- Added option to modify client source for user agent, it now has following options
- Android `(user agent: Customer.io Android Client/2.1.1 (Google Pixel 6; 32) io.customer.remotehabits/1.0)`
- React `(user agent: Customer.io ReactNative Client/2.1.1 (Google Pixel 6; 32) io.customer.remotehabits/1.0)`
- Expo `(user agent: Customer.io Expo …

feat: changes for react native package

---

common-test/src/main/java/io/customer/commontest/BaseTest.kt
common-test/src/main/java/io/customer/commontest/DeviceStoreStub.kt
messagingpush/src/main/java/io/customer/messagingpush/CustomerIOFirebaseMessagingService.kt
sdk/src/main/java/io/customer/sdk/CustomerIO.kt
sdk/src/main/java/io/customer/sdk/data/store/Client.kt
sdk/src/main/java/io/customer/sdk/data/store/DeviceStore.kt
sdk/src/sharedTest/java/io/customer/sdk/data/store/ClientTest.kt

This PR adds support for the changes required to align with iOS SDK and make react native package easier to interact
To fix deep link navigation from notifications, this PR has following changes
- Added option to append SDK version with name in client for user agent
- Android [2.6.3] `(user agent: Customer.io Android Client/2.6.3 (Google Pixel 6; 32) io.customer.remotehabits/1.0)`
- React [3.9.7] `(user agent: Customer.io ReactNative Client/3.9.7 (Google Pixel 6; 32) io.customer.remotehabits/1.0)`
- Expo [7.3.2] `(user agent: Customer.io Expo Client/(7.3.2) (Google Pixel 6; 32) io.customer.remotehabits/1.0)`
- (Other) iOS [4.6.7] `(user agent: Customer.io iOS Client/4.6.7 (Google Pixel 6; 32) io.customer.remotehabits/1.0)`
- Fixed test cases and added new for `Client`
- Added kdocs …

feat: updated client to support react native user agent

---

buildSrc/src/main/kotlin/io.customer/android/Versions.kt

fix: in-app messages stop delivering 

---

buildSrc/src/main/kotlin/io.customer/android/Versions.kt

fix: version bump for gist sdk to resolve messaging not showing bug

---

buildSrc/src/main/kotlin/io.customer/android/Versions.kt

fix: in-app system link causes app reopen

---

.github/workflows/deploy-git-tag.yml
.github/workflows/deploy-maven-central.yml
.github/workflows/promote.yml

Changes the Slack channel for deployment messages to the new mobile-deployments channel See customerio/issues#9014

ci: changes Slack deployment message channel

---

messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
messaginginapp/src/sharedTest/java/io/customer/messaginginapp/ModuleMessagingInAppTest.kt

fix: set gist user token incase identifier exists

---

.editorconfig
base/src/test/java/io/customer/base/extensions/DateExtensionsTest.kt
buildSrc/src/main/kotlin/io.customer/android/Versions.kt
common-test/src/main/java/io/customer/commontest/TestCustomAttributesDataSet.kt
messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
messaginginapp/src/main/java/io/customer/messaginginapp/provider/GistInAppMessagesProvider.kt
messaginginapp/src/main/java/io/customer/messaginginapp/type/InAppEventListener.kt
messaginginapp/src/sharedTest/java/io/customer/messaginginapp/InAppMessagesProviderTest.kt
messaginginapp/src/sharedTest/java/io/customer/messaginginapp/ModuleMessagingInAppTest.kt
messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
scripts/get-ktlint.sh
sdk/src/main/java/io/customer/sdk/api/HttpRequestRunner.kt
sdk/src/main/java/io/customer/sdk/api/interceptors/HeadersInterceptor.kt
sdk/src/main/java/io/customer/sdk/data/model/EventType.kt
sdk/src/main/java/io/customer/sdk/data/moshi/adapter/UnixDateAdapter.kt
sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
sdk/src/main/java/io/customer/sdk/queue/QueueStorage.kt
sdk/src/sharedTest/java/io/customer/sdk/api/HttpRequestRunnerTest.kt
sdk/src/sharedTest/java/io/customer/sdk/data/store/FileTypeTest.kt
sdk/src/sharedTest/java/io/customer/sdk/queue/QueueStorageIntegrationTest.kt
sdk/src/sharedTest/java/io/customer/sdk/repository/SharedPreferenceRepositoryTest.kt
sdk/src/sharedTest/java/io/customer/sdk/repository/SitePreferenceRepositoryTest.kt

closes: https://github.com/customerio/issues/issues/9190

fix: rename in app listener keys

---

sdk/api/sdk.api
sdk/src/main/java/io/customer/sdk/CustomerIO.kt
sdk/src/main/java/io/customer/sdk/CustomerIOConfig.kt
sdk/src/main/java/io/customer/sdk/util/Logger.kt
sdk/src/sharedTest/java/io/customer/sdk/CustomerIOTest.kt
sdk/src/sharedTest/java/io/customer/sdk/extensions/CustomerIOEExtensionsTest.kt

build: refactor config mapping

---

.github/workflows/pr-helper.yml

ci: removed unnecessary warning

---

samples/kotlin_compose/build.gradle.kts
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/MainApplication.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/data/models/User.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/data/persistance/AppDatabase.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/data/persistance/UserDao.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/data/repositories/UserRepository.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/di/DataStoreModule.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/di/DatabaseModule.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/di/RepositoryModule.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/login/LoginRoute.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/util/PreferencesKeys.kt
samples/kotlin_compose/src/main/res/values/strings.xml

chore: added db and di layer for user related features

---

samples/java_layout/build.gradle
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/SampleApplication.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/core/Constants.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/core/MapUtils.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/data/PreferencesDataStore.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/data/PreferencesStoreUtils.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/data/model/User.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/di/ApplicationGraph.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/di/ViewModelFactory.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/support/Optional.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/support/OptionalImpl.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/core/BaseActivity.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/dashboard/DashboardActivity.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/login/LoginActivity.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/user/AuthViewModel.java
samples/java_layout/src/main/res/layout/activity_dashboard.xml
samples/java_layout/src/main/res/layout/activity_login.xml

Part of https://github.com/customerio/issues/issues/9845
- Added SDK dependencies
- Loaded SDK credentials from `local.properties`
- Base DI graph
- Preferences store
- User object
- Factory for ViewModels
- `AuthViewModel` for user authentication
- Basic logic for authentication using splash screen
- Helper classes and functions

chore: java sample di and preferences

---

.gitignore
samples/kotlin_compose/build.gradle.kts
samples/kotlin_compose/src/main/AndroidManifest.xml
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/MainApplication.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/data/sdk/InAppMessageEventListener.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/navigation/AppNavigation.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/components/Configuration.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/util/Logger.kt
samples/kotlin_compose/src/main/res/values/strings.xml

chore: added deep/universal links and in-app in kotlin sample

---

samples/java_layout/build.gradle
samples/kotlin_compose/build.gradle.kts
samples/sample-app.gradle

Helps https://github.com/customerio/issues/issues/9844, https://github.com/customerio/issues/issues/9845
- `sample-app.gradle` file to hold common gradle properties for sample apps
- gradle file updates in sample apps to apply from newly added gradle file

chore: extract common gradle props for sample apps

---

samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/MainActivity.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/navigation/AppNavigation.kt

chore: deep-link handling for in-app in kotlin sample

---

samples/fastlane/Fastfile

I merged [this pr](https://github.com/customerio/customerio-ios/pull/327) which means this code needs updated.

ci: change branch for re-usable Fastfile building sample apps

---

.github/workflows/deploy-sdk.yml

ci: add dependency to fix "sd" command for git tag

---

sdk/src/main/java/io/customer/sdk/CustomerIOConfig.kt
sdk/src/sharedTest/java/io/customer/sdk/CustomerIOTest.kt

There was inconsistency between Docs/iOS and Android

fix: set auto track screen to false by default

---

samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/settings/SettingsActivity.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/tracking/AttributesTrackingFragment.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/tracking/CustomEventTrackingFragment.java
samples/java_layout/src/main/res/values/strings.xml

Part of https://github.com/customerio/issues/issues/9845
- Settings screen updated to not allow any empty value
- Updated text field errors with generic error messages

chore: java sample validations

---

samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/MainActivity.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/navigation/AppNavigation.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/dashboard/Dashboard.kt
samples/kotlin_compose/src/main/res/values/themes.xml

chore: updated code to handle permission in activity level rather compose

---

samples/fastlane/Fastfile

Identical to [iOS pr](https://github.com/customerio/customerio-ios/pull/340)

ci: sample apps user-agent compatible with backend

---

samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/customTrack/CustomAttribute.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/customTrack/CustomEvent.kt

chore: sample app kotlin remove required fields from custom event/attributes

---

samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/dashboard/DashboardActivity.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/settings/SettingsActivity.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/tracking/AttributesTrackingFragment.java
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/tracking/CustomEventTrackingFragment.java
samples/java_layout/src/main/res/values/strings.xml

part of: https://github.com/customerio/issues/issues/9845
- Save settings automatically after restore
- Background Queue settings validations
- Event screen attribute fix
- Validation updates
- Improved support for notification permission if disabled on Android 12 and lower

chore: java sample fixes and improvements

---

Makefile
lefthook.yml
sdk/api/sdk.api
sdk/src/main/java/io/customer/sdk/CustomerIO.kt
sdk/src/main/java/io/customer/sdk/repository/DeviceRepository.kt
sdk/src/sharedTest/java/io/customer/sdk/CustomerIOTest.kt

feat: expose device token

---

.github/workflows/build-sample-apps.yml
samples/java_layout/src/main/AndroidManifest.xml
samples/java_layout/src/main/res/xml/network_security_config.xml
samples/kotlin_compose/src/main/AndroidManifest.xml
samples/kotlin_compose/src/main/res/xml/network_security_config.xml

We need each sample app to work with different CIO workspaces. 
See [status of PR](https://github.com/customerio/customerio-android/pull/236#issuecomment-1626004989). 
Made this before my EOD to get early reviews and ideas on how to fix proxyman config.

ci: sample apps using separate workspaces

---

messaginginapp/build.gradle
sdk/build.gradle

fix: duplicate classes crash on wrappers

---

sdk/src/main/java/io/customer/sdk/repository/DeviceRepository.kt
sdk/src/main/java/io/customer/sdk/repository/ProfileRepository.kt
sdk/src/sharedTest/java/io/customer/sdk/repository/DeviceRepositoryTest.kt
sdk/src/sharedTest/java/io/customer/sdk/repository/ProfileRepositoryTest.kt

fix: prevent empty identifier and device token

---

samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/settings/SettingsActivity.java
samples/java_layout/src/main/res/values/strings.xml
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/settings/Settings.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/settings/SettingsViewModel.kt
samples/kotlin_compose/src/main/res/drawable/baseline_content_copy_24.xml
samples/kotlin_compose/src/main/res/values/strings.xml

chore: added device token in sample apps

---

messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistSdk.kt
messaginginapp/src/sharedTest/java/io/customer/messaginginapp/GistSdkListenersTest.kt

fixes: https://github.com/customerio/customerio-android/issues/245
- Replaced for each loop with iterator to prevent concurrency issues

fix: prevent concurrency issues in in-app listeners

---

sdk/src/main/java/io/customer/sdk/queue/QueueRunRequest.kt
sdk/src/sharedTest/java/io/customer/sdk/queue/QueueRunRequestTest.kt

closes: https://github.com/customerio/customerio-android/issues/248

fix: stack-overflow caused by BQ recursion

---

.github/workflows/manual-deployment.yml

ci: added workflow for manual deployment

---

messagingpush/api/messagingpush.api
messagingpush/src/main/java/io/customer/messagingpush/MessagingPushModuleConfig.kt
messagingpush/src/main/java/io/customer/messagingpush/activity/NotificationClickReceiverActivity.kt
messagingpush/src/main/java/io/customer/messagingpush/config/PushClickBehavior.kt
sdk/api/sdk.api
sdk/src/main/java/io/customer/sdk/CustomerIOConfig.kt

helps: https://github.com/customerio/issues/issues/10830
- Renamed `NotificationClickBehavior` to `PushClickBehavior` as I think this is shorter and still descriptive
- Added config constant for wrappers
- Minor doc updates

refactor: push click behavior rename

---

messagingpush/src/main/AndroidManifest.xml

Added comment to https://github.com/customerio/customerio-android/pull/272 for historical reference.

docs: add comment to latest PR for historical reference

---

.github/workflows/deploy-sdk.yml
.github/workflows/sdk-binary-size.yml
.releaserc.json

helps: https://linear.app/customerio/issue/MBL-157/track-the-binary-size-of-our-android-sdk
- Added workflow to comment SDK binary size change summary on every PR
- Updated workflow to commit SDK size report for every commit merged to `main` before being released

ci: sdk binary size report

---

core/api/core.api
core/build.gradle
core/src/main/kotlin/io/customer/android/core/di/AndroidSDKComponent.kt
core/src/main/kotlin/io/customer/android/core/di/DiGraph.kt
core/src/main/kotlin/io/customer/android/core/di/SDKComponent.kt
core/src/main/kotlin/io/customer/android/core/di/SDKComponentExt.kt
core/src/test/java/io/customer/android/core/DiGraphTest.kt

part of [MBL-273](https://linear.app/customerio/issue/MBL-273/enhance-digraph-for-improved-dependency-management)
- Refactored `DiGraph` to simplify accessing and overriding dependencies
- Added tests to validate `DiGraph` functionality

refactor: improve digraph support

---

common-test/src/main/java/io/customer/commontest/BaseUnitTest.kt
core/src/test/java/io/customer/android/core/di/DiGraphTest.kt

- Updated `DiGraphTest` to run as unit test for quicker results
- Added `BaseUnitTest` class for simple unit tests

test: updated DiGraphTest to unit test

---

samples/java_layout/src/main/java/io/customer/android/sample/java_layout/sdk/CustomerIORepository.java
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/data/models/Configuration.kt

Update the sample apps to utilize the common configuration. Changes to UI and removal of old configurations is going to part of another ticket/PR.

chore: sample app configuration

---

datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesCompatibilityTests.kt
datapipelines/src/test/java/io/customer/datapipelines/core/UnitTest.kt
datapipelines/src/test/java/io/customer/datapipelines/extensions/JsonExt.kt

part of [MBL-284](https://linear.app/customerio/issue/MBL-284/setup-testing-environment-for-data-pipelines-module)
- Added code and extensions to read and validate changes from storage
- Added tests to `DataPipelinesCompatibilityTests` to validate changes

test: add data pipeline json test

---

.github/workflows/test.yml
samples/kotlin_compose/src/androidTest/java/io/customer/android/sample/kotlin_compose/MemoryLeakageInstrumentedTest.kt

changes:
- fixes instrumentation test
- speed up the test by caching snapshots

refactor: instrumentation test

---

core/api/core.api
core/src/main/kotlin/io/customer/sdk/communication/Event.kt
core/src/test/kotlin/io/customer/sdk/core/di/EventBusTest.kt

closes: [MBL-344 : Event types](https://linear.app/customerio/issue/MBL-344/event-types)
- added event types
- updated tests to cater new types

chore: added event types

---

common-test/src/main/java/io/customer/commontest/BaseTest.kt
common-test/src/main/java/io/customer/commontest/util/DispatchersProviderStub.kt
common-test/src/main/java/io/customer/commontest/util/ScopeProviderStub.kt
core/api/core.api
core/build.gradle
core/src/main/kotlin/io/customer/sdk/communication/Event.kt
core/src/main/kotlin/io/customer/sdk/communication/EventBus.kt
core/src/main/kotlin/io/customer/sdk/core/di/AndroidSDKComponent.kt
core/src/main/kotlin/io/customer/sdk/core/util/DispatchersProvider.kt
core/src/main/kotlin/io/customer/sdk/core/util/ScopeProvider.kt
core/src/test/kotlin/io/customer/sdk/core/di/EventBusTest.kt
sdk/api/tracking.api
sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
sdk/src/main/java/io/customer/sdk/di/CustomerIOStaticComponent.kt
sdk/src/main/java/io/customer/sdk/queue/Queue.kt
sdk/src/main/java/io/customer/sdk/util/SimpleTimer.kt

closes: [MBL-316 : Event Bus](https://linear.app/customerio/issue/MBL-316/event-bus)
- Adds EventBus implementation + tests
- Added dependencies in `core`
- Base `Event` class to demonstrate and test

chore: event bus class

---

README.md

docs: [docs-393] update logo/brand in readme

---

common-test/src/main/java/io/customer/commontest/BaseIntegrationTest.kt
core/api/core.api
core/src/main/kotlin/io/customer/sdk/core/di/AndroidSDKComponent.kt
core/src/main/kotlin/io/customer/sdk/core/di/SDKComponent.kt
core/src/main/kotlin/io/customer/sdk/core/di/SDKComponentExt.kt
datapipelines/src/test/java/io/customer/datapipelines/support/core/UnitTest.kt
messaginginapp/src/androidTest/java/io/customer/messaginginapp/MessagingInAppIntegrationTest.kt
messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
messagingpush/src/main/java/io/customer/messagingpush/ModuleMessagingPushFCM.kt
messagingpush/src/main/java/io/customer/messagingpush/di/DiGraphMessagingPush.kt
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/utils/ViewUtils.java
samples/kotlin_compose/src/androidTest/java/io/customer/android/sample/kotlin_compose/MemoryLeakageInstrumentedTest.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/util/extensions/ContextExt.kt

closes: [MBL-334 : Decouple In App Module from Tracking Module](https://linear.app/customerio/issue/MBL-334/decouple-in-app-module-from-tracking-module)
changes:
- Refactoring to android sdk component and its usage 
- Import updates and refactor

chore: refactor android sdk component

---

messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistSdk.kt
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/sdk/CustomerIORepository.java
samples/kotlin_compose/src/androidTest/java/io/customer/android/sample/kotlin_compose/MemoryLeakageInstrumentedTest.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/MainApplication.kt
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/login/LoginViewModel.kt
samples/sample-app.gradle

closes: [MBL-338 : Track In-App Metrics](https://linear.app/customerio/issue/MBL-338/track-in-app-metrics)

chore: remove tracking from sample apps

---

core/api/core.api
core/src/main/kotlin/io/customer/sdk/lifecycle/CustomerIOActivityLifecycleCallbacks.kt
core/src/main/kotlin/io/customer/sdk/lifecycle/LifecycleStateChange.kt
messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistSdk.kt
messagingpush/src/main/java/io/customer/messagingpush/ModuleMessagingPushFCM.kt

alternate implementation for memory leakage.

chore: memory leakage for application lifecycle

---

datapipelines/src/main/kotlin/io/customer/datapipelines/migration/TrackingMigrationProcessor.kt
datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
tracking-migration/api/tracking-migration.api
tracking-migration/src/main/java/io/customer/tracking/migration/MigrationAssistant.kt
tracking-migration/src/main/java/io/customer/tracking/migration/MigrationProcessor.kt
tracking-migration/src/main/java/io/customer/tracking/migration/repository/preference/SitePreferenceRepository.kt

Added device token migration from `sitePreference` to `globalPreference`

chore: added device token migration

---

datapipelines/api/datapipelines.api
datapipelines/src/main/kotlin/io/customer/datapipelines/migration/TrackingMigrationPlugin.kt
datapipelines/src/main/kotlin/io/customer/datapipelines/migration/TrackingMigrationProcessor.kt
tracking-migration/api/tracking-migration.api
tracking-migration/src/main/java/io/customer/tracking/migration/MigrationAssistant.kt
tracking-migration/src/main/java/io/customer/tracking/migration/MigrationProcessor.kt

part of [MBL-413](https://linear.app/customerio/issue/MBL-413/write-automated-tests-for-validating-migration-changes)
- Added `TrackingMigrationPlugin` to append device token and platform in event context
- Updated code to add and remove plugin as needed

chore: fix device token in migration tasks

---

datapipelines/api/datapipelines.api
datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
datapipelines/src/main/kotlin/io/customer/sdk/CustomerIOBuilder.kt
datapipelines/src/main/kotlin/io/customer/sdk/DataPipelineInstance.kt
datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesCompatibilityTests.kt
datapipelines/src/test/java/io/customer/datapipelines/DeviceAttributesTests.kt
datapipelines/src/test/java/io/customer/datapipelines/migration/TrackingMigrationProcessorTest.kt
datapipelines/src/test/java/io/customer/datapipelines/sdk/AndroidLifecyclePluginTests.kt
datapipelines/src/test/java/io/customer/datapipelines/sdk/CustomerIOBuilderTest.kt
datapipelines/src/test/java/io/customer/datapipelines/testutils/core/UnitTestDelegate.kt
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/sdk/CustomerIORepository.java
samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/data/models/Configuration.kt

- parity with iOS builder methods and more simplified method

chore: simplified builder methods

---

.github/workflows/deploy-sdk.yml

ci: fix release workflow

---

datapipelines/api/datapipelines.api
datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/AutomaticActivityScreenTrackingPlugin.kt
messaginginapp/api/messaginginapp.api
messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistSdk.kt
messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/engine/EngineWebView.kt
messaginginapp/src/main/java/io/customer/messaginginapp/state/InAppMessageReducer.kt
messaginginapp/src/main/java/io/customer/messaginginapp/state/InAppMessagingAction.kt
messaginginapp/src/main/java/io/customer/messaginginapp/state/InAppMessagingMiddlewares.kt
messaginginapp/src/test/java/io/customer/messaginginapp/InAppMessagingStoreTest.kt

helps: [MBL-475](https://linear.app/customerio/issue/MBL-475/update-in-app-messaging-module-using-state-management-in-android)

chore: in-app refactor improvements

---

.github/workflows/reusable_build_sample_apps.yml

chore: fix sample app groups action typo

---

.github/dependabot.yml

ci: Updates dependabot.yml to send reviews to current squad

---

docs/dev-notes/DEVELOPMENT.md

docs: remove references to remote habits

---

.github/actions/setup-android/action.yml
.github/workflows/build-sample-apps.yml
.github/workflows/deploy-sdk.yml
.github/workflows/lint.yml
.github/workflows/manual-deployment.yml
.github/workflows/pr-helper.yml
.github/workflows/reusable_build_sample_apps.yml
.github/workflows/sdk-binary-size.yml
.github/workflows/snapshot-release.yml
.github/workflows/test.yml

REF: [DX-516](https://linear.app/customerio/issue/DX-516/update-all-github-action-libraries-to-use-sha-instead-of-version) Pins GitHub Actions as part of DX-516.

DX-516: Pin actions to SHA

---

messaginginapp/src/main/java/io/customer/messaginginapp/gist/data/model/Message.kt
messaginginapp/src/main/java/io/customer/messaginginapp/state/InAppMessagingMiddlewares.kt

closes: https://linear.app/customerio/issue/MBL-1025/middleware-logic-updates-to-act-differently-for-modal-vs-inline-views
changes:
- update in middleware to cate inline messages and emit them

chore: updates in middleware to handle both modal and inline messages 

---

messaginginapp/src/main/java/io/customer/messaginginapp/ui/InAppMessageViewExtensions.kt
messaginginapp/src/main/java/io/customer/messaginginapp/ui/InlineInAppMessageBaseView.kt
messaginginapp/src/test/java/io/customer/messaginginapp/GistSDKTest.kt
messaginginapp/src/test/java/io/customer/messaginginapp/InAppMessagingStoreTest.kt
messaginginapp/src/test/java/io/customer/messaginginapp/state/InAppMessageReducerTest.kt
messaginginapp/src/test/java/io/customer/messaginginapp/testutils/extension/GistExtensions.kt

closes: https://linear.app/customerio/issue/MBL-1021/persistant-messages
changes:
- Fixed the issues with persistent dismissing for persistent messages
- Added tests for persistent messages

chore: fixed persistent issues and added tests

---

messaginginapp-compose/api/messaginginapp-compose.api
messaginginapp-compose/src/main/java/io/customer/messaginginapp/compose/InlineInAppMessage.kt
messaginginapp/api/messaginginapp.api
messaginginapp/src/main/java/io/customer/messaginginapp/type/InlineMessageActionListener.kt
messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/InAppMessageViewController.kt
messaginginapp/src/test/java/io/customer/messaginginapp/ui/controller/InAppMessageViewControllerTest.kt
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/inline/InlineMessageActionListenerImpl.kt
samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/inline/compose/ComposeInlineExampleFragment.kt

changes:
- updated parameters to align with [iOS callbacks](https://docs.customer.io/integrations/sdk/ios/in-app/inline-in-app/#2-listen-for-events)

chore: updated callbacks parameters to align with iOS

---

AGENTS.md

- Add AGENTS.md file with comprehensive development guidance for AI coding agents working with the Android SDK
- Covers Android-specific architecture, build commands, testing patterns, and code style guidelines
- Includes Kotlin version compatibility requirements and dependency management guidance
- Documents sample app usage for development and testing workflows
- Provides module structure overview and development best practices
Enables AI coding agents to work more effectively with the Android SDK codebase by understanding project conventions, 
build processes, and architectural patterns.

chore: guidelines added for agents
