customerio/customerio-android

- docs/dev-notes/DEVELOPMENT.md
We can add this snippet back in the future but it's not needed for now since we're not following it entirely.
> docs: remove "development workflow" section

- .github/workflows/snapshot-release.yml
- Get rid of the `develop` branch and make a snapshot release on each feature branch
> ci: snapshot release on each branch

- README.md
customer.io/docs/sdk/android contains all the information in this readme. I've trimmed it down to _just_ the bare installation instructions and linked back to the docs site in a few places.
We can trim more if we want, but I _think_ this gets us there.
> docs: trim readme to basic instructions

- app/src/main/java/io/customer/example/MainActivity.kt
- sdk/src/main/java/io/customer/sdk/data/moshi/CustomerIOParser.kt
- sdk/src/main/java/io/customer/sdk/data/moshi/adapter/BigDecimalAdapter.kt
- sdk/src/main/java/io/customer/sdk/data/moshi/adapter/SupportedAttributesAdapter.kt
- sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
- sdk/src/test/java/io/customer/sdk/repositories/AttributesRepositoryTest.kt
SDK was adding scientific notation in numbers because the JSON parser library would convert it into `double`. This is the known behavior of the [library](https://github.com/square/moshi/issues/192). 
Updating default behavior to convert all numbers into BigDecimal, with this we can avoid the use of scientific notation and resolve our issue.
Helpscout [ticket](https://secure.helpscout.net/conversation/1761542700/147582)
> fix: added support for big decimal

- .github/workflows/deploy-maven-central.yml
- .github/workflows/deploy-sdk.yml
- .releaserc.json
The way that deployments currently happen for this project are:
1. Deploy to Sonatype server (maven central)
2. Create new git tag and push to GitHub along with CHANGELOG.md file update. 
If for some reason step #2 fails, we have to run step #2 manually from a computer. You can't simply re-run the CI workflow to try to make a deployment again. 
This is because once you push the SDK to the Sonatype server in step #1, you can't push that same SDK version (1.0.0) again. The server will deny the request. 
But, if we swap the order of the steps 1 and 2 above, if there is ever an error during deployment of either step, you can simply re-run the CI step to try again. Allowing each team member to be able to fix the issues themselves. 
That's what this PR does: swaps the steps 1 and 2 above.
> ci: deploy to maven central after git tag

- .github/workflows/snapshot-release.yml
- sdk/src/main/AndroidManifest.xml
- sdk/src/main/res/xml/network_security_config.xml
Potential bug fix for a customer. 
This PR does include a modification to the snapshot deployment script as the previous script was not working (semantic-release was not running a dry run) so I changed the snapshot to use the git commit hash to always be unique. We can leave this script change in this PR, or remove it and fix that in a future fix if there is a better idea to fix it. I wanted to get a snapshot build made for the customer to test for us.
> fix: allow http requests in host app

- base/src/main/java/io/customer/base/comunication/Action.kt
- base/src/main/java/io/customer/base/comunication/Call.kt
- base/src/main/java/io/customer/base/utils/ActionUtils.kt
- buildSrc/src/main/kotlin/io.customer/android/Dependencies.kt
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOFirebaseMessagingService.kt
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushReceiver.kt
- sdk/src/main/java/io/customer/sdk/CustomerIO.kt
- sdk/src/main/java/io/customer/sdk/extensions/StringExtensions.kt
- sdk/src/test/java/io/customer/sdk/extensions/StringExtensionsTest.kt
fixes https://github.com/customerio/issues/issues/7111
> fix: added alternative route to fetch screen name for automatic tracking

- codecov.yml
- sdk/src/main/java/io/customer/sdk/api/HttpRequestRunner.kt
- sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
QA testing found that registering push tokens HTTP request is not happening. I was able to reproduce it and this fixed it. Retrofit was throwing an error saying it was not able to create a `@Body` request object for `DeviceRequest`. I found out that it was because none of our custom Moshi JsonAdapter classes were being added to Retrofit so our `CustomAttributesJsonAdapter` was not being used. 
> fix: register device tokens http request

- .releaserc.json
- scripts/update-version.sh
I am trying to make the deployment process better documented and resilient to problems. Part of that process is allowing the deployment process to be done manually if needed. 
This PR simply makes some naming changes to be consistent with the other SDKs. As [documented here](https://github.com/customerio/customerio-ios/pull/175/). 
> ci: make update version script easier for manual use

- .github/slack-payloads/deploy_code_fail.json
- .github/slack-payloads/deploy_code_success.json
- .github/slack-payloads/deploy_git_tag_fail.json
- .github/slack-payloads/deploy_git_tag_success.json
- .github/slack-payloads/promote_fail.json
- .github/workflows/deploy-git-tag.yml
- .github/workflows/deploy-maven-central.yml
- .github/workflows/promote.yml
I found a new Slack notification plugin that seems to be more helpful for deployment success and failures. I installed it in the React Native SDK project and wanted to do the same here. 
> ci: better slack notifications during deployment process

- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
- messagingpush/src/main/java/io/customer/messagingpush/data/communication/CustomerIOPushNotificationCallback.kt
- messagingpush/src/sharedTest/java/io/customer/messagingpush/ModuleMessagingConfigTest.kt
Closes: [83](https://github.com/customerio/customerio-android/issues/83)
- Added `onNotificationComposed` to `CustomerIOPushNotificationCallback` that notifies client app whenever notification composition is complete (except `PendingIntent`)
- Added docs
```
addCustomerIOModule(ModuleMessagingPushFCM(
MessagingPushModuleConfig.Builder().apply {
this.setNotificationCallback(object : CustomerIOPushNotificationCallback {
override fun onNotificationComposed(
payload: CustomerIOParsedPushPayload,
builder: NotificationCompat.Builder
) {
// Do whatever you want to do with NotificationBuilder, e.g.
builder.setSmallIcon(R.drawable.ic_small_push_notification)
}
})
}.build()
))
```
---
Complete each step to get your pull request merged in. [Learn more about the workflow this project …
> feat: added option to customize push notification from app

- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
- messagingpush/src/main/java/io/customer/messagingpush/extensions/ApplicationInfoExtensions.kt
- messagingpush/src/main/java/io/customer/messagingpush/extensions/ContextExtensions.kt
- messagingpush/src/main/java/io/customer/messagingpush/extensions/StringExtensions.kt
Fixes: [8156](https://github.com/customerio/issues/issues/8156)
- Following the optiones defined by [FCM](https://firebase.google.com/docs/cloud-messaging/android/receive#edit-the-app-manifest), added support to modify small icon and color for notification using `AndroidManifest`
- The preference of icon color is follows (Same as FCM)
1. Icon defined in notification payload
2. Icon defined in `AndroidManifest`
3. Application Icon
- Notification color has similar preference except that no color is applied unless mentioned explicitly
1. Color defined in notification payload
2. Color defined in `AndroidManifest`
3. None
- Added helper extension methods in `push-messaging` module
> **NOTE: The changes help having a similar behavior in both FCM and our SDK. Both message and data notifications …
> feat: added support to modify notification small icon

- common-test/src/main/java/io/customer/commontest/BaseTest.kt
- messagingpush/src/main/java/io/customer/messagingpush/extensions/ContextExtensions.kt
- messagingpush/src/main/java/io/customer/messagingpush/extensions/StringExtensions.kt
- sdk/api/sdk.api
- sdk/build.gradle
- sdk/src/main/java/io/customer/sdk/CustomerIO.kt
- sdk/src/main/java/io/customer/sdk/CustomerIOShared.kt
- sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
- sdk/src/main/java/io/customer/sdk/di/CustomerIOSharedComponent.kt
- sdk/src/main/java/io/customer/sdk/util/Logger.kt
- sdk/src/main/java/io/customer/sdk/util/StaticSettingsProvider.kt
- sdk/src/sharedTest/java/io/customer/sdk/CustomerIOSharedTest.kt
- sdk/src/sharedTest/java/io/customer/sdk/util/LoggerTest.kt
- Added a top level graph named `CustomerIOSharedComponent` to hold instances of classes that can be initialized without any dependency. Currently, the graph contains only following classes and can hold more where needed.
- `Logger`
- `DispatchersProvider`
- Added `CustomerIOShared` class to initialize our SDK on first access without any dependency and can be used to minimise challenged for delayed initializations, particularly helpful when building wrapper SDKs for non native frameworks
- Added test cases to verify log modifications and and shared instance behavior
> feat: added shared instance for independent components

- sdk/src/main/java/io/customer/sdk/queue/QueueRunner.kt
- sdk/src/main/java/io/customer/sdk/queue/QueueStorage.kt
- sdk/src/main/java/io/customer/sdk/util/JsonAdapter.kt
Closes: [8311](https://github.com/customerio/issues/issues/8311)
- Removed all direct usages of `fromJson` and `fromJsonList` from the SDK and replaced with nullable calls
- Since we could not make non nullable parsing methods private because of being `inline`, added docs to discourage using them directly
- Updated `QueueRunner` to expect nullable tasks and fail gracefully
> fix: updated json adapter usage to safe parsing

- common-test/src/main/java/io/customer/commontest/DeviceStoreStub.kt
- sdk/src/main/java/io/customer/sdk/data/store/Client.kt
- sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
- sdk/src/sharedTest/java/io/customer/sdk/data/store/ClientTest.kt
Helps: [8515](https://github.com/customerio/issues/issues/8515)
- Uses wrapper SDK version from client value attributes passed in `DeviceStore`
- Added support for Flutter client
> fix: cio sdk version attribute using client value

- buildSrc/src/main/kotlin/io.customer/android/Versions.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/provider/GistApiProvider.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/provider/GistInAppMessagesProvider.kt
- messaginginapp/src/sharedTest/java/io/customer/messaginginapp/InAppMessagesProviderTest.kt
Closes: [8614](https://github.com/customerio/issues/issues/8614)
- Updates Gist SDK version to `2.3.0`
- Updated `InAppMessagesProvider` and `GistApiProvider` to support changes from Gist SDK
- Fixed test cases
> fix: in-app messages instant delivery

- messaginginapp/api/messaginginapp.api
- messaginginapp/src/main/java/io/customer/messaginginapp/provider/GistInAppMessagesProvider.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/type/InAppEventListener.kt
- messaginginapp/src/sharedTest/java/io/customer/messaginginapp/InAppMessagesProviderTest.kt
Removing extra parameter from in-app event listener that [the team did not mention is needed](https://github.com/customerio/customerio-ios/pull/211#issuecomment-1332281565).
The parameter has also been removed in iOS SDK.
> fix: remove currentRoute parameter in in-app event listener

- buildSrc/src/main/kotlin/io.customer/android/Versions.kt
- messaginginapp/api/messaginginapp.api
- messaginginapp/build.gradle
- messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/provider/GistApiProvider.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/provider/GistInAppMessagesProvider.kt
- messaginginapp/src/sharedTest/java/io/customer/messaginginapp/ModuleMessagingInAppTest.kt
- messagingpush/api/messagingpush.api
- messagingpush/src/main/java/io/customer/messagingpush/ModuleMessagingPushFCM.kt
> feat: in-app feature no longer requires orgId

- buildSrc/src/main/kotlin/io.customer/android/Versions.kt
> fix: use maven style dependency range syntax

- .github/workflows/deploy-sdk.yml
Related to #169, we actually want to keep the `beta` branch around for deployments for a little while longer.
> ci: add beta branch to deploy workflow

- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
In the case of custom payload, 
```
{
"message":{
"notification": {
"body" : "Meet scientific Yogi & Empathy Expert Thiemo️",
"title" : "Yoga + Meditation + Science = :bulb:️️",
"image": "https://userimg-assets.customeriomail.com/images/client-env-101262/1676545327104_thiemo_01GSCY703G786FJE0F5FT34H0N.jpeg"
},
"data": {
"screen": "/users/9b906b6c-3152-4083-87d4-455d9d6e4e13?utm_source=cio&utm_medium=push&utm_campaign=thiemo_push&utm_content=9b906b6c-3152-4083-87d4-455d9d6e4e13&utm_term={{delivery_id}}"
}
}
}
```
If the app is in the foreground, `Service` would receive payload, and we need to check for `notification.image`. 
More information : https://customerio.slack.com/archives/C02580R06/p1676625992450419
Complete each step to get your pull request merged in. [Learn more about the …
> fix: image not shown when image url in notification payload

- messagingpush/api/messagingpush.api
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOFirebaseMessagingService.kt
Helps: https://github.com/customerio/issues/issues/9477
- Updated `CustomerIOFirebaseMessagingService` access to open so we can inherit it in wrapper SDKs
> fix: update CustomerIOFirebaseMessagingService to open

- sdk/src/main/java/io/customer/sdk/data/store/FileStorage.kt
closes: https://github.com/customerio/issues/issues/9530
- Moved reading file text code inside `try-catch` to prevent crashing the app
- Added null safety operator for recently nullable file list method
> NOTE: This method doesn't fix the root cause for files being not found. We're not yet able to reproduce this, but the code change helps preventing customer apps from crashing
> fix: prevent crash for file not found exception

- docs/dev-notes/KOTLIN-BINARY-VALIDATOR.md
- docs/dev-notes/KotlinBinaryValidator
Moved from the `mobile` repo to `android` one. 
> docs: kotlin binary validator

- sdk/src/main/java/io/customer/sdk/CustomerIO.kt
Due to lifecycle differences, multiple instances of the `application` lifecycle would be added. So we need to unregister old instances of callbacks and also garbage collect any other instance of before. 
> fix: added cleanup of previously instance before creating new one

- messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
- sdk/api/sdk.api
- sdk/src/main/java/io/customer/sdk/data/request/DeliveryEvent.kt
- sdk/src/main/java/io/customer/sdk/queue/Queue.kt
- sdk/src/main/java/io/customer/sdk/repository/TrackRepository.kt
- sdk/src/sharedTest/java/io/customer/sdk/repository/TrackRepositoryTest.kt
closes: https://github.com/customerio/issues/issues/8657
> feat: in app click tracking

- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOFirebaseMessagingService.kt
- sdk/src/main/java/io/customer/sdk/CustomerIO.kt
- sdk/src/main/java/io/customer/sdk/CustomerIOActivityLifecycleCallbacks.kt
- sdk/src/main/java/io/customer/sdk/queue/Queue.kt
fixes: https://github.com/customerio/issues/issues/9483
- Updated `instanceOrNull` method to support modules initialization
- Updated `CustomerIOFirebaseMessagingService` to initialize push module when we initialize SDK using `context`
> fix: push opened metrics tracked on Android 12

- sdk/src/main/java/io/customer/sdk/di/DiGraph.kt
While testing, we noticed there are multiple instances of `Queue` being created even in `Native SDK` even though it's using `getSingletonInstanceCreate` method. On further logging, it was observed, that it might be due to multithreading so we making this method `synchronized` would fix it. 
> fix: multiple Queue instances being created

- samples/java_layout/build.gradle
- samples/java_layout/src/main/AndroidManifest.xml
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/common/SimpleFragmentActivity.java
- samples/java_layout/src/main/res/layout/activity_dashboard.xml
- samples/java_layout/src/main/res/layout/activity_login.xml
- samples/java_layout/src/main/res/values/strings.xml
Part of https://github.com/customerio/issues/issues/9845
- Deep links support for app scheme URLs
- `java-sample://settings`
- `java-sample://events/custom`
- `java-sample://attributes/device`
- `java-sample://attributes/profile`
- Deep links support for universal scheme URLs
- https://www.java-sample.com/settings
- https://www.java-sample.com/events/custom
- https://www.java-sample.com/attributes/device
- https://www.java-sample.com/attributes/profile
- Fixes and improvements in deep link handling
- Fixed user agent width and text alignment
> chore: java sample universal scheme deep links

- .github/workflows/build-sample-apps.yml
- samples/sample-app.gradle
Sample apps builds generated by actions used `local.properties` inside the app, but the code assumed the `local.properties` file should be used from root project which resulted in inconsistency and apps failing to load properties when uploaded for distribution
- Updated gradle file to use `local.properties` located in `samples` folder so same file can be reused by all apps and can be kept separate from SDK properties
> ci: sample apps local props path

- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/common/SimpleFragmentActivity.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/dashboard/DashboardActivity.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/login/LoginActivity.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/settings/SettingsActivity.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/tracking/AttributesTrackingFragment.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/tracking/CustomEventTrackingFragment.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/utils/ViewUtils.java
- samples/resources/values/appium.xml
- samples/sample-app.gradle
part of: https://github.com/customerio/issues/issues/9845
helps: https://github.com/customerio/issues/issues/9844
- Sets content description for views which is common practice for automation tests, in case we need to changes this later because of some technical limitation, we can do it in a separate PR
- Added `appium.xml` containing tags for all views
- Added `appium.xml` as resource for all sample app so it can be reused
> chore: java sample appium tags

- messaginginapp/consumer-rules.pro
- samples/java_layout/build.gradle
- samples/kotlin_compose/build.gradle.kts
Gist proguard settings didn't get copied over when in-app module code was migrated from Gist SDK into the CIO SDK. This PR adds those proguard rules back. Also enables proguard on sample apps so we can better test Release builds like customers are. 
Fixes: https://github.com/customerio/opsbugs/issues/3627
> fix: in-app messaging proguard rules missing

- messagingpush/api/messagingpush.api
- messagingpush/src/main/AndroidManifest.xml
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
- messagingpush/src/main/java/io/customer/messagingpush/MessagingPushModuleConfig.kt
- messagingpush/src/main/java/io/customer/messagingpush/activity/NotificationClickReceiverActivity.kt
- messagingpush/src/main/java/io/customer/messagingpush/config/NotificationClickBehavior.kt
- messagingpush/src/main/java/io/customer/messagingpush/extensions/ApplicationInfoExtensions.kt
- messagingpush/src/main/java/io/customer/messagingpush/util/DeepLinkUtil.kt
helps: https://github.com/customerio/issues/issues/10830
- `NotificationClickReceiverActivity` for handling notification clicks
- `NotificationClickBehavior` for customizing notification click behavior
- `DeepLinkUtil` updates to avoid adding unwanted flags to intents
- Intent flag changes in PR are not fully final and still being tested with all sample apps, which may force changes for flags in future PRs
- Options and default values for `NotificationClickBehavior` may be re-reviewed after feature changes are complete so we have clear picture of there implementation and behavior with different sample apps
> chore: add activity to handle push click

- .github/workflows/deploy-sdk.yml
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
- messagingpush/src/main/java/io/customer/messagingpush/MessagingPushModuleConfig.kt
- messagingpush/src/main/java/io/customer/messagingpush/activity/NotificationClickReceiverActivity.kt
- messagingpush/src/main/java/io/customer/messagingpush/di/DiGraphMessagingPush.kt
- messagingpush/src/main/java/io/customer/messagingpush/processor/PushMessageProcessor.kt
- messagingpush/src/main/java/io/customer/messagingpush/processor/PushMessageProcessorImpl.kt
- messagingpush/src/main/java/io/customer/messagingpush/util/DeepLinkUtil.kt
- messagingpush/src/sharedTest/java/io/customer/messagingpush/CustomerIOPushNotificationHandlerTest.kt
- messagingpush/src/sharedTest/java/io/customer/messagingpush/ModuleMessagingConfigTest.kt
- messagingpush/src/sharedTest/java/io/customer/messagingpush/activity/NotificationClickReceiverActivityTest.kt
- messagingpush/src/sharedTest/java/io/customer/messagingpush/processor/PushMessageProcessorTest.kt
helps: https://github.com/customerio/issues/issues/10830
- Moved code out of `NotificationClickReceiverActivity` to `PushMessageProcessor` for reusability and better testing
- Added tests for `CustomerIOPushNotificationHandler`, `ModuleMessagingConfig` and `PushMessageProcessor`
> refactor: move push click handling to processor

- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/engine/EngineWebView.kt
fixes: https://github.com/customerio/customerio-android/issues/270
Testing:
- This is how i replicated, created a new emulator 
- Run the command 
```
adb shell pm uninstall --user 0 com.google.android.webview
```
Verified the app didn't crash when an in-app was recieved.
> fix: added exception handling for when browser doesn't exist

- messagingpush/src/main/AndroidManifest.xml
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
helps: https://github.com/customerio/issues/issues/10830
- Added `android:launchMode="singleTop"` to `NotificationClickReceiverActivity` as without it, Android OS does not launch activity again in one session if the activity was launched recently from earlier notification
> fix: update notification receiver activity launchMode

- messaginginapp/api/messaginginapp.api
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/data/listeners/Queue.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/data/model/Message.kt
Fixes issue: https://github.com/customerio/issues/issues/11663
> fix: add priority field to message and sorting by priority within local store

- .github/workflows/build-sample-apps.yml
- .github/workflows/deploy-sdk.yml
The iOS SDK experienced a deployment failure on `main` because of a GH Action that we depend on. 
I installed a workaround in the iOS SDK until the GH action gets fixed. This PR applies the same workaround here.
> ci: fix installing sd tool needed for deployment

- messaginginapp/src/main/java/io/customer/messaginginapp/gist/data/listeners/Queue.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistSdk.kt
The idea is to keep track of the shown messages by queueId (which is unique per message) and skip the shown ones
This is based on the same solution applied for gist-web: https://github.com/customerio/gist-web/pull/26
Task: https://github.com/customerio/issues/issues/11967
> fix: ensure messages are only shown once

- messaginginapp/src/main/java/io/customer/messaginginapp/gist/data/listeners/Queue.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistSdk.kt
Updates the polling interval remotely through the new `X-Gist-Queue-Polling-Interval` header.
Part of: [INAPP-12243](https://linear.app/customerio/issue/INAPP-12243/update-the-in-app-sdks-to-configure-polling-based-on-remote)
> feat: use new header to set polling interval

- .github/workflows/deploy-sdk.yml
helps: https://linear.app/customerio/issue/MBL-157/track-the-binary-size-of-our-android-sdk
- Fixes broken CI task by add `IS_DEVELOPMENT` to `env` for `deploy-sdk`
> ci: fix for binary size report

- .github/workflows/deploy-sdk.yml
helps: https://linear.app/customerio/issue/MBL-157/track-the-binary-size-of-our-android-sdk
- Added `publishToMavenLocal` so local version can be fetched
> ci: fix for binary size report gradle task

- .github/workflows/deploy-sdk.yml
helps: https://linear.app/customerio/issue/MBL-157/track-the-binary-size-of-our-android-sdk
- Added `setup-android` so binary size gradle task can utilize `apkanalyzer`
> ci: setup android for binary size gradle task

- buildSrc/src/main/kotlin/io.customer/android/Versions.kt
- sdk/consumer-rules.pro
closes: 
Added consumer rules for following (couldn't bump their version to add rules automatically as they are compiled with Kotlin 1.9X and hence client apps needs to bump their kotlin version)
- Moshi
- Retrofit
Updated [version](https://square.github.io/okhttp/changelogs/changelog_4x/#version-4110) for OKHTTP as it contains the latest rules.
> fix: added consumer rules for R8 full mode

- common-test/build.gradle
- common-test/src/main/java/io/customer/commontest/BaseTest.kt
- common-test/src/main/java/io/customer/commontest/module/CustomerIOGenericModule.kt
- core/api/core.api
- core/src/main/kotlin/io/customer/android/core/di/DiGraph.kt
- core/src/main/kotlin/io/customer/android/core/module/CustomerIOGenericModule.kt
- core/src/main/kotlin/io/customer/android/core/module/CustomerIOModule.kt
- core/src/main/kotlin/io/customer/android/core/module/CustomerIOModuleConfig.kt
- datapipelines/build.gradle
- messaginginapp/api/messaginginapp.api
- messaginginapp/build.gradle
- messaginginapp/src/main/java/io/customer/messaginginapp/MessagingInAppModuleConfig.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
- messaginginapp/src/sharedTest/java/io/customer/messaginginapp/ModuleMessagingInAppTest.kt
- messagingpush/api/messagingpush.api
- messagingpush/build.gradle
- messagingpush/src/main/java/io/customer/messagingpush/MessagingPushModuleConfig.kt
- messagingpush/src/main/java/io/customer/messagingpush/ModuleMessagingPushFCM.kt
- messagingpush/src/sharedTest/java/io/customer/messagingpush/ModuleMessagingConfigTest.kt
- messagingpush/src/sharedTest/java/io/customer/messagingpush/processor/PushMessageProcessorTest.kt
- sdk/api/tracking.api
- sdk/build.gradle
- sdk/src/main/java/io/customer/sdk/CustomerIO.kt
- sdk/src/main/java/io/customer/sdk/CustomerIOConfig.kt
- sdk/src/main/java/io/customer/sdk/di/CustomerIOComponent.kt
- sdk/src/main/java/io/customer/sdk/di/CustomerIOSharedComponent.kt
- sdk/src/main/java/io/customer/sdk/di/CustomerIOStaticComponent.kt
- sdk/src/sharedTest/java/io/customer/sdk/CustomerIOTest.kt
part of [MBL-243](https://linear.app/customerio/issue/MBL-243/initialize-the-sdk)
- Moved base module classes from `tracking` to `core`
- Moved base DiGraph class from `tracking` to `core` so we can create desired graphs in `core`
> refactor: base module and digraph classes to core

- core/api/core.api
- core/src/main/kotlin/io/customer/android/core/di/AndroidSDKComponent.kt
- core/src/main/kotlin/io/customer/android/core/di/SDKComponent.kt
- core/src/main/kotlin/io/customer/android/core/di/SDKComponentExt.kt
part of [MBL-273](https://linear.app/customerio/issue/MBL-273/enhance-digraph-for-improved-dependency-management)
- Introduced `SDKComponent` static DI graph to decouple dependencies from SDK initialization
- Added `AndroidSDKComponent` to hold dependencies specific to Android OS and context
> chore: add static and android di graphs

- datapipelines/src/main/kotlin/io/customer/datapipelines/DataPipelinesModule.kt
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/sdk/CustomerIORepository.java
- samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/MainApplication.kt
- samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/data/models/Configuration.kt
part of [MBL-214](https://linear.app/customerio/issue/MBL-214/identify-a-profile)
- Added custom logger to `analytics` to ensure that log configurations align with the SDK
- Updated sample apps to set `logLevel` when initializing the SDK with new SDK builder
> chore: add logger to analytics in datapipelines module

- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/sdk/DataPipelineInstance.kt
- datapipelines/src/main/kotlin/io/customer/sdk/android/CustomerIO.kt
- samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/customTrack/CustomEvent.kt
- samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/dashboard/Dashboard.kt
- samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/login/Login.kt
- samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/settings/Settings.kt
closes: https://linear.app/customerio/issue/MBL-216/track-a-screen-view-manually
- Added public APIs to track screen events
- Update sample apps to utilize the new APIs
Tests are going to follow in the next PR when the base setup PR is merged.
> feat: added screen APIs

- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesCompatibilityTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
adds compatibility and interaction tests for `track` and `screen`
closes:
- https://linear.app/customerio/issue/MBL-212/track-an-event-manually
- https://linear.app/customerio/issue/MBL-216/track-a-screen-view-manually
> chore: add track screen tests

- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesCompatibilityTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/core/UnitTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/extensions/JsonExt.kt
- datapipelines/src/test/java/io/customer/datapipelines/support/UserTraits.kt
part of [MBL-214](https://linear.app/customerio/issue/MBL-214/identify-a-profile)
- Added more tests to `DataPipelinesInteractionTests` and `DataPipelinesCompatibilityTests` for identify profile
- Moved `OutputReaderPlugin` out of `UnitTest` to avoid being misused
- Added helper extensions and `UserTraits` class to test package
> test: identify user profile

- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/datapipelines/config/DataPipelinesModuleConfig.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/AutomaticActivityScreenTrackingPlugin.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/StringExtensions.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIOBuilder.kt
- datapipelines/src/main/kotlin/io/customer/sdk/android/CustomerIO.kt
- datapipelines/src/test/java/io/customer/datapipelines/extensions/StringExt.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/CustomerIOBuilderTest.kt
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/sdk/CustomerIORepository.java
- samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/data/models/Configuration.kt
closes: https://linear.app/customerio/issue/MBL-286/expose-plugin-for-automatic-screen-tracking
Includes:
- Config to enable/disable feature
- Plugin to fire events based on activity lifecycle
- Sample app changes
> feat: add support for automatic activity screen tracking

- buildSrc/src/main/kotlin/io.customer/android/Dependencies.kt
- datapipelines/build.gradle
- datapipelines/src/test/java/io/customer/datapipelines/core/UnitTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/AndroidLifecyclePluginTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/CustomerIOBuilderTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/utils/Analytics.kt
- datapipelines/src/test/java/io/customer/datapipelines/utils/TestRunPlugin.kt
- scripts/android-config.gradle
closes: https://linear.app/customerio/issue/MBL-309/application-lifecycle-events
tests cover:
- Verify with application state changes lifecycle callbacks are received 
- The lifecycle events are being tracked that we take responsibility of
> chore: application lifecycle tests

- core/api/core.api
- core/src/main/kotlin/io/customer/sdk/core/di/AndroidSDKComponent.kt
- core/src/main/kotlin/io/customer/sdk/data/store/GlobalPreferenceStore.kt
- core/src/main/kotlin/io/customer/sdk/data/store/PreferenceStore.kt
- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/ContextPlugin.kt
- datapipelines/src/main/kotlin/io/customer/sdk/DataPipelineInstance.kt
- datapipelines/src/main/kotlin/io/customer/sdk/android/CustomerIO.kt
part of [MBL-217](https://linear.app/customerio/issue/MBL-217/device-management)
- Implemented and exposed public APIs to track device with attributes
- Added `GlobalPreferenceStore` to store common attributes e.g. device token
```kotlin
CustomerIO.instance().registeredDeviceToken
CustomerIO.instance().deviceAttributes = mapOf("name" to "Brand", "os" to 33)
CustomerIO.instance().registerDeviceToken(token)
CustomerIO.instance().deleteDeviceToken
```
Tests and sample app updates are not included in this PR, will be added in upcoming PRs soon.
> feat: track device with attributes

- samples/java_layout/build.gradle
- samples/kotlin_compose/build.gradle.kts
- samples/sample-app.gradle
I realized it's harder to connect both of these sample apps to different workspaces because of the way we currently fetch keys. So I made some changes that allow us to provide optional different keys for the sample apps, with fallback to current format so we can reuse the same keys as well. These changes shouldn't break anything on CI or on local machines for any developer.
- Updated the sample apps' `build.gradle` script to prefer keys with prefix
- If the prefix is not provided or prefix keys are missing, it falls back to keys without prefix
- Both sample apps are updated to mention their prefix
```
apiKey=API_KEY
siteId=SITE_ID
cdpApiKey=CDP_API_KEY
javaLayout_cdpApiKey=JAVA_CDP
kotlinCompose_cdpApiKey=KOTLIN_CDP
```
> chore: sample apps api keys with prefix

- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- Used new logger reference in nested log helper objects to avoid memory leaks
- Reset static DIGraph in `clearInstance`
> chore: fix memory leaks in data pipelines module

- .github/workflows/snapshot-release.yml
[SEC-36](https://linear.app/customerio/issue/SEC-36/gha-run-shell-injection-vulnerability)
Using `github` variables in a GHA `run` step introduces a run shell injection vulnerability.
> ci: use intermediate env var in run

- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesCompatibilityTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/CustomerIOBuilderTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/support/core/UnitTest.kt
part of: [MBL-215](https://linear.app/customerio/issue/MBL-215/automatic-device-attributes-collection-and-user-agent-updates)
I noticed we have been using both `Mockito` and `MockK` in Data Pipelines module. While this isn't necessarily an issue, we should only use both if needed. For functionalities that can be handled by both, we should stick to our preferred choice for consistency. I prefer `MockK` over `Mockito` because:
- Our project codebase is mostly Kotlin
- `MockK` is more Kotlin-friendly and easier to integrate
- It has a DSL-like syntax and is easy to adopt in Kotlin
- It allows mocking/spying methods for final classes
I haven't removed `Mockito` from the module yet, I only updated it to see how it works. If everything goes well, we can later remove `Mockito` from the …
> chore: use mockk instead of mockito in data pipelines

- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/AutoTrackDeviceAttributesPlugin.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/ContextPlugin.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
part of: [MBL-215](https://linear.app/customerio/issue/MBL-215/automatic-device-attributes-collection-and-user-agent-updates)
- Updated `ContextPlugin` to remove undesired values from the `context` object
- Added `AutoTrackDeviceAttributesPlugin` to include auto-tracked device attributes
- Updated device update event to include auto-tracked device attributes in event properties
**_Please refer to mentioned ticket for JSON output comparison between iOS and Android_**
> chore: implement auto track device attributes

- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIOBuilder.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesCompatibilityTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/extensions/TrackMetricExtTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/AndroidLifecyclePluginTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/CustomerIOBuilderTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/support/core/JUnitTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/support/core/RobolectricTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/support/core/TestConfiguration.kt
- datapipelines/src/test/java/io/customer/datapipelines/support/core/UnitTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/support/stubs/UnitTestLogger.kt
- datapipelines/src/test/java/io/customer/datapipelines/support/utils/Plugins.kt
part of: [MBL-215](https://linear.app/customerio/issue/MBL-215/automatic-device-attributes-collection-and-user-agent-updates)
- Moved the creation of `AndroidSDKComponent` earlier with `CustomerIOBuilder` initialization so tests don't have to explicitly create it and can reuse it to override dependencies before initializing the module.
- Added `JUnitTest` and `RobolectricTest` classes to avoid rewriting setup code and to make writing both types of tests easier
- Updated `UnitTest` for more flexibility. Tests should avoid directly inheriting it and use `JUnitTest` or `RobolectricTest` instead
- Added `TestConfiguration` to wrap setup parameters in a single class for flexibility
- Added a DSL-like option for convenient initialization of `TestConfiguration`
- Fixed parent classes for tests
> chore: allow modifying config in data pipelines test setup

- messagingpush/api/messagingpush.api
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOCloudMessagingReceiver.kt
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOFirebaseMessagingService.kt
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
- messagingpush/src/main/java/io/customer/messagingpush/ModuleMessagingPushFCM.kt
- messagingpush/src/main/java/io/customer/messagingpush/activity/NotificationClickReceiverActivity.kt
- messagingpush/src/main/java/io/customer/messagingpush/di/DiGraphMessagingPush.kt
- messagingpush/src/main/java/io/customer/messagingpush/extensions/StringExtensions.kt
- messagingpush/src/main/java/io/customer/messagingpush/provider/FCMTokenProviderImpl.kt
- messagingpush/src/main/java/io/customer/messagingpush/util/AppLifecycleCallbacks.kt
closes: [MBL-333 : Decouple Push Module from Tracking Module](https://linear.app/customerio/issue/MBL-333/decouple-push-module-from-tracking-module)
- removes tracking modules usage from push
- remove digraph and static digraph usage from push
Not included:
- removed tracking dependency 
- update test to not utilize tracking
> chore: removed tracking usage from push

- messaginginapp/api/messaginginapp.api
- messaginginapp/src/main/java/io/customer/messaginginapp/MessagingInAppModuleConfig.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/di/DIGraphMessagingInApp.kt
- messaginginapp/src/sharedTest/java/io/customer/messaginginapp/ModuleMessagingInAppTest.kt
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/sdk/CustomerIORepository.java
- samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/MainApplication.kt
part of: [MBL-377](https://linear.app/customerio/issue/MBL-377/decouple-tests-from-tracking)
- Updated `MessagingInAppModuleConfig.Builder` to include required options (i.e. `siteId` and `region`)
- Removed unused code from `ModuleMessagingInApp`
- Updated sample apps
- Minor improvements in related code
> chore: inapp config builder

- messagingpush/api/messagingpush.api
- messagingpush/src/main/java/io/customer/messagingpush/MessagingPushModuleConfig.kt
- messagingpush/src/main/java/io/customer/messagingpush/data/communication/CustomerIOPushNotificationCallback.kt
- messagingpush/src/main/java/io/customer/messagingpush/processor/PushMessageProcessorImpl.kt
- messagingpush/src/main/java/io/customer/messagingpush/util/DeepLinkUtil.kt
- messagingpush/src/test/java/io/customer/messagingpush/ModuleMessagingConfigTest.kt
closes: [MBL-396 : Revisit Push Module Config to Eliminate Redundant Configurations](https://linear.app/customerio/issue/MBL-396/revisit-push-module-config-to-eliminate-redundant-configurations)
improves customer experience and dev experience.
> chore: updated constructor to not account for task builder

- core/build.gradle
- core/src/test/java/io/customer/sdk/communication/EventBusTest.kt
- core/src/test/java/io/customer/sdk/core/di/DiGraphTest.kt
- core/src/test/java/io/customer/sdk/core/util/LoggerTest.kt
part of [MBL-394](https://linear.app/customerio/issue/MBL-394/decouple-common-tests-from-tracking-module)
- Removed test dependencies from module's gradle file as they are now included in the common gradle file for test dependencies
- Updated tests to match package of their respective classes
- Updated tests to work with `common-test` updates
All tests for `core` module are passing ✅
See [parent PR](https://github.com/customerio/customerio-android/pull/373) for more details and context.
> refactor: core module test classes

- datapipelines/build.gradle
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelineEventBusInteractionTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesCompatibilityTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/DeviceAttributesTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/extensions/StringExtensionsTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/extensions/TrackMetricExtensionsTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/AndroidLifecyclePluginTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/CustomerIOBuilderTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/testutils/core/DataPipelinesTestConfig.kt
- datapipelines/src/test/java/io/customer/datapipelines/testutils/core/IntegrationTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/testutils/core/JUnitTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/testutils/core/UnitTestDelegate.kt
part of [MBL-394](https://linear.app/customerio/issue/MBL-394/decouple-common-tests-from-tracking-module)
- Removed test dependencies from module's gradle file as they are now included in the common gradle file for test dependencies
- Updated tests to match package of their respective classes
- Updated tests to work with `common-test` updates
- Updated `DataPipelinesTestConfig` as an extension of `TestConfig` that helps setting up `datapipelines` tests with module specific configuration
All tests for `datapipelines` module are passing ✅
See [parent PR](https://github.com/customerio/customerio-android/pull/373) for more details and context.
> refactor: datapipelines module test classes

- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/ContextPlugin.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/PluginExtensions.kt
- datapipelines/src/test/java/io/customer/datapipelines/plugins/ContextPluginTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/testutils/extensions/JsonExt.kt
part of [MBL-220](https://linear.app/customerio/issue/MBL-220/migration-for-track-background-queue-identify-and-events)
- Updated `ContextPlugin` to avoid rewriting token if one already exists
- This is to prevent data corruption with the old token already added to JSON
- Moved helpful extension from tests to production code that helps append the token to event JSON
- Added tests to validate changes
> chore: prefer existing device token

- tracking-migration/api/tracking-migration.api
- tracking-migration/src/main/java/io/customer/tracking/migration/queue/QueueQueryRunner.kt
- tracking-migration/src/main/java/io/customer/tracking/migration/queue/QueueRunRequest.kt
helps: https://linear.app/customerio/issue/MBL-395/migration-for-stored-data
- Removed unnecessary information from the Queue runner
- Queue runner just fetches the task, perform migration and get deleted
> chore: update queue to remove unused logic

- core/src/main/kotlin/io/customer/sdk/data/store/PreferenceStore.kt
- tracking-migration/api/tracking-migration.api
- tracking-migration/src/main/java/io/customer/tracking/migration/repository/preference/SitePreferenceRepository.kt
part of [MBL-220](https://linear.app/customerio/issue/MBL-220/migration-for-track-background-queue-identify-and-events)
- Updated core `PreferenceStore` to allow extending in other modules
- Refactored and added `SitePreferenceRepository` to `migration` module to fetch values added by `tracking` module in older releases
> chore: add site pref repo to migration module

- common-test/src/main/java/io/customer/commontest/core/TestConstants.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/AutoTrackDeviceAttributesPlugin.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/util/EventNames.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesCompatibilityTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/DeviceAttributesTests.kt
part of [MBL-220](https://linear.app/customerio/issue/MBL-220/migration-for-track-background-queue-identify-and-events)
- Added `EventNames` to hold constants for event names so they can be reused
- Updated code and tests to use newly added constants
> refactor: move event names to constants

- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistSdk.kt
With our in-app rendering move from flutter to html, we don't need to pre-load flutter engine to download assets. 
more context here: https://customerio.slack.com/archives/C036FTE6UJ0/p1721046751535539
resolves the ANR issue too: https://github.com/customerio/customerio-android/issues/361
> fix: remove gist pre-loading

- datapipelines/src/main/kotlin/io/customer/datapipelines/migration/TrackingMigrationProcessor.kt
- tracking-migration/api/tracking-migration.api
- tracking-migration/src/main/java/io/customer/tracking/migration/extensions/JsonExtensions.kt
- tracking-migration/src/main/java/io/customer/tracking/migration/request/MigrationTask.kt
- tracking-migration/src/main/java/io/customer/tracking/migration/util/JsonAdapter.kt
part of [MBL-413](https://linear.app/customerio/issue/MBL-413/write-automated-tests-for-validating-migration-changes)
- Update `MigrationTask` to always have an `identifier` (update for metric events mainly)
- Fixed minor parsing issues in migration `JsonAdapter`
> chore: fix migration json adapter

- tracking-migration/api/tracking-migration.api
- tracking-migration/src/main/java/io/customer/tracking/migration/MigrationAssistant.kt
- tracking-migration/src/main/java/io/customer/tracking/migration/di/MigrationSDKComponent.kt
- tracking-migration/src/test/java/io/customer/tracking/migration/MigrationAssistantTest.kt
- tracking-migration/src/test/java/io/customer/tracking/migration/testutils/core/JUnitTest.kt
part of [MBL-413](https://linear.app/customerio/issue/MBL-413/write-automated-tests-for-validating-migration-changes)
- Moved `CoroutineScope` in `MigrationSDKComponent` so it can be overridden in tests
- Updated `MigrationAssistant` internal constructor to allow overriding `MigrationSDKComponent` for tests
- Added base `JUnitTest` class in migration tests for convenience
- Added tests for `MigrationAssistant`
> test: migration assistant class

- .github/workflows/build-sample-apps.yml
TS would like to use a sample app that points to CDP API. To help, I thought we could give them access to Android sample app builds on the cdp branch. 
IMO, even beyond this scenario, I think making builds on all feature branches for testing by the team is a good idea.
> ci: build sample apps on feature branches

- common-test/src/main/java/io/customer/commontest/extensions/AssertionExtensions.kt
- tracking-migration/src/main/java/io/customer/tracking/migration/util/JsonAdapter.kt
- tracking-migration/src/test/java/io/customer/tracking/migration/queue/QueueTest.kt
- tracking-migration/src/test/java/io/customer/tracking/migration/testutils/core/IntegrationTest.kt
- tracking-migration/src/test/java/io/customer/tracking/migration/testutils/data/MigrationDataSet.kt
- tracking-migration/src/test/java/io/customer/tracking/migration/util/JsonAdapterTest.kt
part of [MBL-425](https://linear.app/customerio/issue/MBL-425/identify-and-improve-test-coverage-in-migration-module)
- Added more tests for `JsonAdapter` to validate error scenarios
- Added basic tests for running `Queue`
- Added helper methods, base test class and sample json for invalid data to facilitate writing tests
Queue runner tests will be added separately later.
> test: migration json adapter invalid data

- datapipelines/src/main/kotlin/io/customer/datapipelines/migration/TrackingMigrationProcessor.kt
- samples/sample-app.gradle
Tasks migrated from previous versions sometimes missed enrichment closure because analytics queue was not started before, this prevented us from attaching correct timestamp to those events
- Subscribe to analytics store so we can wait for analytics queue to start and allows enrichment closure to run every time
- Removed unnecessary migration dependency from sample apps
> chore: fix timestamp in migration tasks

- datapipelines/src/main/kotlin/io/customer/datapipelines/migration/TrackingMigrationProcessor.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- Fixes memory leak in `TrackingMigrationProcessor` by relying on `CustomerIO.instance` instead of `this`
> chore: fix memory leak in migration processor

- .github/workflows/deploy-sdk.yml
There was an issue in CI workflow where it commits the version file, but woudn't checkout to it before pushing it to maven central.
> fix: android user agent version

- messaginginapp/api/messaginginapp.api
- messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/di/DIGraphMessagingInApp.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/ModuleMessagingInAppTest.kt
- messagingpush/api/messagingpush.api
- messagingpush/src/main/java/io/customer/messagingpush/di/DiGraphMessagingPush.kt
Since we decoupled all modules from `CustomerIO` class and moved them to `core` module, modules were moved to the `SDKComponent` class. This broke some public APIs accessed through `SDKComponent` and made some of our documentation outdated (e.g., dismissing in-app messaging). To fix this, we had two options:
I think this is the most feasible option, so I opted for this.
I don't think recommending customers to use `SDKComponent` is a very good idea, so I opted for option 1.
- Exposed in-app module through the `CustomerIO` object for customer ease
- Exposed in-app module through module object directly to help Java customers
- Marked `SDKComponent` methods exposing these modules as internal
- [Docs link that is currently broken](https://customer.io/docs/sdk/android/in-app/in-app-event-listene …
> feat: public api for dismiss message

- messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/ModuleMessagingInAppTest.kt
changes:
- Before sending click event to journeys ignore actions that are for close.
> chore: ignore close callbacks for clicked

- messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/state/InAppMessagingMiddlewares.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/ModuleMessagingInAppTest.kt
closes: [MBL-516: Android SDK (4x?) is not tracking responses for in-app message clicks / not tracking all click data](https://linear.app/customerio/issue/MBL-516/android-sdk-4x-is-not-tracking-responses-for-in-app-message-clicks-not)
`action_name`, `action_value` were being used in tracking API calls, whereas data pipeline required the keys to be `actionName` and `actionValue`
> fix: updates tracking keys

- messaginginapp/api/messaginginapp.api
- messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/data/model/Message.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistModalActivity.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/state/InAppMessagingMiddlewares.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/type/InAppMessage.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/ModuleMessagingInAppTest.kt
changes:
- ignore embedded messages that were blocking the queue from being processed
- move GistProperties as part of `Message`
> chore: ignore embed and cleanup properties

- common-test/src/main/AndroidManifest.xml
- common-test/src/main/java/io/customer/commontest/config/TestArgument.kt
- common-test/src/main/java/io/customer/commontest/core/BaseTest.kt
- core/api/core.api
- core/src/androidTest/AndroidManifest.xml
- core/src/androidTest/java/io/customer/sdk/data/store/AndroidManifestClientTest.kt
- core/src/main/AndroidManifest.xml
- core/src/main/kotlin/io/customer/sdk/core/di/AndroidSDKComponent.kt
- core/src/main/kotlin/io/customer/sdk/core/di/SDKComponentExt.kt
- core/src/main/kotlin/io/customer/sdk/core/extensions/ContextExtensions.kt
- core/src/main/kotlin/io/customer/sdk/data/store/Client.kt
- core/src/test/java/io/customer/sdk/data/store/ClientTest.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIOBuilder.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/testutils/core/IntegrationTest.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/testutils/core/JUnitTest.kt
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
- messagingpush/src/test/java/io/customer/messagingpush/testutils/core/IntegrationTest.kt
- messagingpush/src/test/java/io/customer/messagingpush/testutils/core/JUnitTest.kt
- tracking-migration/src/test/java/io/customer/tracking/migration/testutils/core/IntegrationTest.kt
- tracking-migration/src/test/java/io/customer/tracking/migration/testutils/core/JUnitTest.kt
part of [MBL-522](https://linear.app/customerio/issue/MBL-522/user-agent-rn-android)
- Moved `Client` class out of `AndroidSDKComponent` constructor and made it a singular dependency, allowing for decoupling
- Simplified `Client` class by removing sealed implementation
- Updated `Client` class to create user-agent client based on meta-data provided in `AndroidManifest`
- Added and used extensions to fetch meta-data from `AndroidManifest` and fixed the deprecated method warning for `ApplicationInfo`
- Added tests to verify the changes
- Removed `ClientArgument` from `TestArgument` as it is no longer needed
- `Client` is no longer dependent on SDK initialization
- `Client` will always remain the same, regardless of which classes initialize the SDK and register `AndroidSDKComponent`
- …
> chore: use meta-data for user agent client

- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- datapipelines/src/main/kotlin/io/customer/sdk/DataPipelineInstance.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
closes: [MBL-528: Android SDK should consistently add userId in delete token payload](https://linear.app/customerio/issue/MBL-528/android-sdk-should-consistently-add-userid-in-delete-token-payload)
Since event are asynchronous, we can have `userId` null before `deleteDevice` access the value of `userId`. So we should enrich the delete device event with `userId` so it always have that value.
> fix: add userId for deleteToken

- samples/java_layout/src/main/res/values/strings.xml
Completes [Update app name to “Android Native”](https://linear.app/customerio/issue/MBL-558/update-app-name-to-android-native)
This PR changes the Android native sample app name to be "Native". This makes it easier to differentiate the app in the device launcher from other sample apps.
I've chosen to make the name "Native" instead of "Android Native" to avoid it being truncated.
| Truncated version  | Non-truncated version |
| ------------- | ------------- |
| <img width="87" alt="app-name-after-truncated" src="https://github.com/user-attachments/assets/e335fb6e-554a-4159-9f6b-394d47e87a4a"> | <img width="83" alt="app-name-after" src="https://github.com/user-attachments/assets/a40f494e-1663-4746-af16-500d80e9bb26">  |
| Before  | After |
| ------------- | ------------- |
| <img width="94" …
> chore: Update JavaLayout sample app name to "Native"

- messaginginapp/api/messaginginapp.api
- messaginginapp/src/main/java/io/customer/messaginginapp/di/DIGraphMessagingInApp.kt
- messagingpush/api/messagingpush.api
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
- messagingpush/src/main/java/io/customer/messagingpush/di/DiGraphMessagingPush.kt
closes: [MBL-545: Push metrics tracking (iOS & Android - RN)](https://linear.app/customerio/issue/MBL-545/push-metrics-tracking-ios-and-android-rn)
exposes module config to be used in wrappers.
> chore: expose module config

- common-test/src/main/java/io/customer/commontest/util/UnitTestLogger.kt
- core/api/core.api
- core/src/main/kotlin/io/customer/sdk/core/util/Logger.kt
- core/src/test/java/io/customer/sdk/core/util/CioLogLevelTest.kt
- core/src/test/java/io/customer/sdk/core/util/LoggerTest.kt
- Updated `Logger` to expose log dispatcher, allowing wrapper SDKs to listen to it and forward logs to their relevant consoles if needed
- Added and fixed relevant tests for `Logger` and `CioLogLevel` classes
> chore: expose console logger callback

- common-test/src/main/java/io/customer/commontest/core/BaseTest.kt
- core/api/core.api
- core/src/main/kotlin/io/customer/sdk/core/di/DiGraph.kt
- core/src/main/kotlin/io/customer/sdk/core/di/SDKComponentExt.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIOBuilder.kt
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOCloudMessagingReceiver.kt
- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOFirebaseMessagingService.kt
- messagingpush/src/main/java/io/customer/messagingpush/activity/NotificationClickReceiverActivity.kt
- Renamed `registerAndroidSDKComponent` to `ensureAndroidComponent` for clearer purpose
- Called the renamed method from all entry points (push services, activities) to ensure Android component is always initialized before accessing any of its dependencies
- Removed unused, deprecated methods from `DiGraph`, as they were intended for SDK use only
> chore: ensure Android component is initialized from services

- .github/workflows/build-sample-apps.yml
- .github/workflows/deploy-sdk.yml
- .github/workflows/snapshot-release.yml
This PR update the SD setup Github action to use the [latest version](https://github.com/kenji-miyake/setup-sd/releases/tag/v2.0.0) instead of the fork.
> chore: Use latest version of setup-sd Github action

- messaginginapp/src/main/java/io/customer/messaginginapp/gist/data/NetworkUtilities.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/data/listeners/Queue.kt
closes: https://linear.app/customerio/issue/MBL-495/move-to-v2-apis-of-gist-and-add-sdk-reporting
changes:
- Upgrade user queue endpoint path to v2
- Added SDK version and platform in request headers
> chore: move to v2 for user queue request and user agent in headers

- .github/workflows/reusable_build_sample_apps.yml
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/utils/ViewUtils.java
- samples/java_layout/src/main/res/layout/activity_dashboard.xml
- samples/java_layout/src/main/res/layout/activity_login.xml
- samples/sample-app.gradle
This PR updates the build info we show on sample apps. The changes aims to make those build info useful to the development team and other stakeholders determining how the sample app they are using was built. It also helps the development team reproduce the same build when they get issues or reports.
This is the version of the SDK that the sample app is using, it can have the following values:
- A version "x.y.z" when a released SDK version was used
- "as source code (branch name)" when the SDK was built as source code from a certain branch
- "as source code (local development)" when it was built locally on a developer's machine
The date and time when the sample app was built, displayed in local time zone of the user
The branch from which the sample app was built
The default workspace that …
> chore: Improve sample apps build info

- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/data/model/CustomerIOSDKConfig.java
This PR changes the sample app config value of "Test Mode" to "No"
The motivation is that this by default aligns more closely to the settings our customers would be using when integrating the SDK into their apps.
> chore: Change sample app config default value for Test Mode to "NO"

- samples/fastlane/Fastfile
This PR updates sample apps version for a branch to the following:
Given the branch is: elmorabea/MBL-647-update-sample-app-version
Old version: elmorabea/MBL-647-update-sample-app-version
New version: elmorabea.MBL-647-update-sample-app-version
This is to avoid parsing issues on the CIO portal of app versions reported having forward slashes in them.
> chore: Update sample app version to include dots instead of forwrad slashes coming form branch names

- messagingpush/src/main/java/io/customer/messagingpush/ModuleMessagingPushFCM.kt
closes: [MBL-695](https://linear.app/customerio/issue/MBL-695/crash-with-illegalargumentexception)
fixes: #466 
- Wrapped `intent.extras` in `ModuleMessagingPushFCM` lifecycle callbacks with try-catch block to prevent potential crashes on older Android versions
This change will not trigger a release since issue reports are low but will be included in the next planned release.
> chore: handle intent extras safely

- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/engine/EngineWebView.kt
Reintroduces bridge function to pass messages between SDK and Renderer
Fixes issue: https://linear.app/customerio/issue/MBL-721/mobile-in-app-crashes-after-updating-from-version-3x-to-44-of-android
> fix: Fixes issue with legacy renderer bridge

- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/data/model/CustomerIOSDKConfig.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/sdk/CustomerIORepository.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/settings/InternalSettingsActivity.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/settings/SettingsActivity.java
- samples/java_layout/src/main/res/layout/activity_settings.xml
- samples/java_layout/src/main/res/values/strings.xml
part of: [MBL-755](https://linear.app/customerio/issue/MBL-755/add-config-to-android-sdk)
- Updated Java sample app to allow `screenViewUse` configuration to be modified from the settings page for testing purposes
- Set `screenViewUse` default behavior to align with SDK settings
> chore: update java sample app with screen view configuration

- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
closes: [MBL-738: Android - Handle device registration when switching from profile with empty string/null identifier.](https://linear.app/customerio/issue/MBL-738/android-handle-device-registration-when-switching-from-profile-with)
handles the case, where if profile attributes are added before the identifying the profile, `userId` was set to empty string.
> chore: handle the case of empty identifier

- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/datapipelines/config/ScreenView.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/ScreenFilterPlugin.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIOBuilder.kt
- datapipelines/src/test/java/io/customer/datapipelines/config/ScreenViewTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/plugins/ScreenFilterPluginTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/CustomerIOBuilderTest.kt
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/data/model/CustomerIOSDKConfig.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/settings/SettingsActivity.java
- samples/java_layout/src/main/res/layout/activity_settings.xml
- samples/java_layout/src/main/res/values/strings.xml
part of: [MBL-755](https://linear.app/customerio/issue/MBL-755/add-config-to-android-sdk)
- Refactored `ScreenView` from enum to sealed class for greater flexibility in future updates
- Added tests to ensure proper parsing of `ScreenView` from strings
- Updated sample app and relevant tests to align with these changes
- `All` -> Sends all screen events to the server (same as before) - Default behavior
- `InApp` -> Retains screen events locally for in-app use only
**Kotlin**
```kotlin
CustomerIOBuilder(...)
.screenViewUse(ScreenView.InApp)
.build()
```
**Java**
```java
CustomerIOBuilder(...)
.screenViewUse(ScreenView.InApp.INSTANCE)
.build()
```
> chore: update screenview to sealed class

- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/datapipelines/config/DataPipelinesModuleConfig.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/config/ScreenView.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/ScreenFilterPlugin.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIOBuilder.kt
- datapipelines/src/test/java/io/customer/datapipelines/config/ScreenViewTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/plugins/ScreenFilterPluginTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/CustomerIOBuilderTest.kt
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/data/model/CustomerIOSDKConfig.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/sdk/CustomerIORepository.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/settings/InternalSettingsActivity.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/settings/SettingsActivity.java
- samples/java_layout/src/main/res/layout/activity_settings.xml
- samples/java_layout/src/main/res/values/strings.xml
part of: [MBL-755](https://linear.app/customerio/issue/MBL-755/add-config-to-android-sdk)
- Added `screenViewUse` enum option to allow disable sending screen view events to server and use them locally only
- Added `ScreenFilterPlugin` to filter events based on the `screenViewUse` configuration
- Added tests to ensure functionality
- `Analytics` -> Sends all screen events to the server (same as before) - Default behavior
- `InApp` -> Retains screen events locally for in-app use only
```kotlin
CustomerIOBuilder(...)
.screenViewUse(ScreenView.InApp)
.build()
```
> feat: add option to disable screen view usage

- buildSrc/src/main/kotlin/io.customer/android/Dependencies.kt
- buildSrc/src/main/kotlin/io.customer/android/Versions.kt
- datapipelines/build.gradle
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/AutomaticApplicationLifecycleTrackingPlugin.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/util/UiThreadRunner.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- datapipelines/src/test/java/io/customer/datapipelines/plugins/AutomaticApplicationLifecycleTrackingPluginTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/AndroidLifecyclePluginTests.kt
Completes [MBL-526
](https://linear.app/customerio/issue/MBL-526/add-application-foregrounded-lifecycle-event-in-android-sdk)
This PR adds the missing application lifecycle event `Application Foregrounded`.
Our wrapper SDKs are initialized later in the app lifecycle, so they miss the initial `onCreate()` -> `onStart()` -> `onResume()` for the first activity in the application. That makes `Acitvity` lifecycle callbacks not usable for us.
- Our SDKs already pull `AndroidX` lifecycle dependency `2.6.1`, so that's why I choose to include it with that specific version
- In ReactNative the `Plugin#setup()` method is not called on the main thread which causes the `lifecycle#addObserver()` call to not work, that's why I'm explicitly running it on UI thread …
> chore: Create a plugin that tracks application lifecycle foreground event

- .github/workflows/test.yml
Currently when the PR is created the instrumentation tests would run perfectly, but on any changes to PR causing re-run of action would result in the emulator not booting and resulting in instrumentation tests not being run. 
This PR fixes that issue.
> chore: fix instrumentation test re-runs

- .github/workflows/reusable_build_sample_apps.yml
- samples/fastlane/Fastfile
part of: [MBL-710](https://linear.app/customerio/issue/MBL-710/single-app-per-platform-distributed-to-firebase)
blocked by: https://github.com/customerio/customerio-ios/pull/847
- Updated `Build Sample Apps` action to push only primary app to relevant channels
- Updated `get_build_test_groups` call to pass arguments to match with implementation from iOS repository
Please refer to linked ticket for detailed expectations regarding channel distribution.
> chore: build primary sample app

- .github/workflows/reusable_build_sample_apps.yml
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/buildinfo/BuildInfoMetadata.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/buildinfo/BuildInfoMetadataUtils.java
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/utils/ViewUtils.java
- samples/sample-app.gradle
part of [MBL-746](https://linear.app/customerio/issue/MBL-746/easy-to-understand-build-info)
- Updated CI workflow to include workspace name in build information
- Updated build info to match screenshot attached in linked ticket
- Added dedicated class and utility functions to primary sample app for easier modification and extraction of build info
- Updated gradle script to include required values in build configurations
| Local (with specific SDK version) |  CI (without specific SDK version) |
|-|-|
| ![img_local](https://github.com/user-attachments/assets/ceb1e12d-de17-47eb-9680-fcd1eba5698e) | ![img_ci](https://github.com/user-attachments/assets/250209ec-3bc5-4240-9185-9304e5e7372c) |
> chore: update sample app build info

- .github/workflows/reusable_build_sample_apps.yml
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/buildinfo/BuildInfoMetadata.java
- Fixed fallback value for `branchName` in primary sample app to match with other sample apps
- Updated workflow to add fallback for cases where tags are not fetched properly
| Before |  After |
|-|-|
| ![img_before](https://github.com/user-attachments/assets/aa3d8cdb-ba43-4079-a25d-a5bffbf51c3d) | ![img_after](https://github.com/user-attachments/assets/3d06b9d7-44a0-459c-a535-d737c5df95f2) |
> chore: fix branch name fallback

- .github/workflows/deploy-sdk.yml
A dependabot PR was breaking slack plugin changes were merged, which is breaking workflow. This PR fixes it.
> chore: fix slack dependency changes in workflows 

- .github/workflows/reusable_build_sample_apps.yml
- samples/fastlane/Fastfile
part of: [MBL-750](https://linear.app/customerio/issue/MBL-750/slack-notifications-on-new-builds)
- Integrated common GitHub Action to send slack notifications when a sample app build completes
- Updated relevant GitHub Action and lane to extract necessary values for triggering the notification
**_Example messages can be seen in slack channels used for notifications_**
> chore: send slack notification on sample app build

- docs/dev-notes/DEVELOPMENT.md
- docs/dev-notes/TROUBLESHOOTING.md
- Added `TROUBLESHOOTING.md` with steps to resolve
- Gradle CLI failures caused by JDK 21 in newer Android Studio versions
- Commit hook failures due to Gradle JVM version mismatch
- Linked troubleshooting guide in `DEVELOPMENT.md` under Troubleshooting section to make it easier to locate
> docs: add troubleshooting guide for jdk 17 issues

- datapipelines/src/main/kotlin/io/customer/datapipelines/extensions/JsonExtensions.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- datapipelines/src/main/kotlin/io/customer/sdk/DataPipelineInstance.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/plugins/CustomerIODestinationTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/util/SanitizeNullsForJsonTest.kt
closes: [MBL-955](https://linear.app/customerio/issue/MBL-955/[bug]-passing-nested-null-attribute-crashes-android-in-react-native)
- Added `sanitizeNullsForJson()` extension to recursively replace all `null` values with `JsonNull` in `CustomAttributes` for `Map` and `List` before forwarding to `analytics`
- Added unit tests to validate the behavior of new extension
- Added tests on `CustomerIO.instance` to validate end-to-end behavior
- Updated Datapipeline method to cater `Map<String,Any?>` so they can cater cases of both, `CustomeAttribute` and `mapof type <string, any?>` 
Crash on `main` before this fix:
```kotlin
CustomerIO.instance().track(
"Add to Cart",
mapOf(
"item" to mapOf(
"id" to "100",
"name" to "Mobile",
"discount" to null,
),
)
)
```
> fix: support null handling in nested structures

- messaginginapp/api/messaginginapp.api
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistModalActivity.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/InAppMessageBaseView.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/InAppMessageViewEventsListener.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/ModalInAppMessageView.kt
- messaginginapp/src/main/res/layout/activity_gist.xml
part of: [MBL-1027](https://linear.app/customerio/issue/MBL-1027/refactor-gistview-for-modal-and-inline-in-app-message-reuse)
- Removed `Gist` naming convention from base views and listeners related to in-app message display:
- Renamed `GistView` to `InAppMessageBaseView` - an abstract base class for both modal and inline in-app messages
- Renamed `GistViewListener` to `InAppMessageViewEventsListener` for clarity
- Added `ModalInAppMessageView` as final view class for displaying and managing modal in-app message logic
- Replaced `GistView` with `ModalInAppMessageView` and used it for displaying modal in-app messages (no functional changes)
> refactor: rename GistView to base in-app view

- .github/workflows/build-sample-app-for-sdk-release.yml
- .github/workflows/deploy-sdk.yml
Closes: [MBL-1053](https://linear.app/customerio/issue/MBL-1053/auto-create-testbed-releases-for-every-sdk-release)
This PR triggers a sample apps public release build after the SDK has been deployed successfully so that internal stakeholders always have up to date versions to test with.
I am not entirely sure if the package will be immediately available after publishing before it can be used to build the sample app or we need a delay. Starting out with immediate trigger and we can revise later if the build fails.
> chore: Trigger sample apps public builds after deployment is successful

- messaginginapp/api/messaginginapp.api
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/data/model/Message.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/engine/EngineWebView.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/state/InAppMessagingState.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/InlineInAppMessageBaseView.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/testutils/extension/GistExtensions.kt
part of: [MBL-989](https://linear.app/customerio/issue/MBL-989/showhide-the-xml-based-view)
- Moved `instanceId` in `Message` class from constructor to a property to avoid it affecting equality checks and triggering unnecessary store events
- Added `releaseResources` method to `EngineWebView` to properly clean up `WebView` after use
- Updated `InAppMessageState` to print as expected by overriding `toString` directly as data classes were previously overriding it implicitly
- Updated `InlineInAppMessageBaseView` to dispatch `DisplayMessage` and clean up `EngineWebView` when it is no longer needed
> chore: clean up EngineWebView and related improvements

- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/ui/core/BaseFragmentContainerActivity.kt
part of: [MBL-1088](https://linear.app/customerio/issue/MBL-1088/persist-inline-in-app-message-on-orientation-change)
In Java sample app, `BaseFragmentContainerActivity` was readding fragment in `LiveData` observer every time the app returned from background. This led to full UI recreation and loss of state including inline messages being destroyed, making testing unreliable.
- Added a boolean flag to prevent same fragment from being re-added when returning from background
No SDK changes, only the sample app is updated.
1. Open Inline Examples screen
2. Send and wait for an inline message to appear
3. Put the app in background
4. Bring it back to foreground
5. Inline message should remain visible
1. Open any Tracking screen (e.g. Custom Event)
2. Enter some input text
3. Put the app in …
> chore: fix unnecessary UI recreation in Java sample app

- .github/workflows/reusable_build_sample_apps.yml
in the last automatic publishing or sample app release, I noticed the wrong version is being used and it seems its because Git would only have access to the tags that were included in the initial checkout, which could be incomplete or outdated.
> chore: fetch tags before setting the version

- docs/dev-notes/DEVELOPMENT.md
Please checkout the read me added for more about what this is about.
This will be linked to wrapper SDKs to help test native Android SDK changes with wrapper SDKs.
> chore: Update docs to publish SDK locally to Maven Local

- core/src/main/kotlin/io/customer/sdk/core/di/SDKComponent.kt
- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/datapipelines/config/DataPipelinesModuleConfig.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/config/ScreenView.kt
- datapipelines/src/main/kotlin/io/customer/datapipelines/di/SDKComponentExt.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIOBuilder.kt
- datapipelines/src/main/kotlin/io/customer/sdk/SdkInitializationLogger.kt
- datapipelines/src/test/java/io/customer/datapipelines/config/DataPipelinesModuleConfigTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/config/ScreenViewTest.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/CustomerIOBuilderTest.kt
- datapipelines/src/test/java/io/customer/sdk/SdkInitializationLoggerTest.kt
- messagingpush/api/messagingpush.api
- messagingpush/src/main/java/io/customer/messagingpush/MessagingPushModuleConfig.kt
- messagingpush/src/main/java/io/customer/messagingpush/di/DiGraphMessagingPush.kt
- messagingpush/src/main/java/io/customer/messagingpush/logger/PushNotificationLogger.kt
- messagingpush/src/main/java/io/customer/messagingpush/provider/FCMTokenProviderImpl.kt
- messagingpush/src/test/java/io/customer/messagingpush/MessagingPushModuleConfigTest.kt
- messagingpush/src/test/java/io/customer/messagingpush/logger/PushNotificationLoggerTest.kt
Part of: [MBL-1075](https://linear.app/customerio/issue/MBL-1075/update-push-notifications-logging-for-android)
Closes: [MBL-1117](https://linear.app/customerio/issue/MBL-1117/update-initialization-logs)
This PR implements log definitions as defined in the log definitions repo https://github.com/customerio/mobile-log-definitions/pull/6
- Creates an SDK initialization logger and push wrappers for convenience 
- Adds logs for SDK init and SDK modules init and Google play services checks
- Added unit test for the wrapper logger
- Logs after implementation are as follows
```
[CIO] D  [Init] Creating new instance of CustomerIO SDK version: 4.5.8...
[CIO] D  [Init] Initializing SDK module DataPipelines with config: DataPipelinesModuleConfig(cdpApiKey='[Redacted]', flushAt=20, flushInterval=30, …
```
> chore: Align push initilization logs with definitions

- datapipelines/src/main/kotlin/io/customer/datapipelines/di/SDKComponentExt.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIOBuilder.kt
- datapipelines/src/main/kotlin/io/customer/sdk/DataPipelinesLogger.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/sdk/CustomerIOBuilderTest.kt
- datapipelines/src/test/java/io/customer/sdk/DataPipelinesLoggerTest.kt
- messagingpush/api/messagingpush.api
- messagingpush/src/main/java/io/customer/messagingpush/di/DiGraphMessagingPush.kt
- messagingpush/src/main/java/io/customer/messagingpush/logger/PushNotificationLogger.kt
- messagingpush/src/main/java/io/customer/messagingpush/provider/FCMTokenProviderImpl.kt
- messagingpush/src/test/java/io/customer/messagingpush/logger/PushNotificationLoggerTest.kt
- messagingpush/src/test/java/io/customer/messagingpush/provider/FCMTokenProviderTest.kt
Part of: [MBL-1075](https://linear.app/customerio/issue/MBL-1075/update-push-notifications-logging-for-android)
Closes: [MBL-1118](https://linear.app/customerio/issue/MBL-1118/update-initialization-logs)
This PR implements log definitions as defined in the log definitions repo https://github.com/customerio/mobile-log-definitions/pull/7
- Transforms the initialization logger into a DataPipelines logger
- Adds logs for pulling, storing and registering push token
- Added unit test for the wrapper logger
- Logs after implementation are as follows
```
[CIO] D  [Init] Creating new instance of CustomerIO SDK version: 4.5.8...
[CIO] D  [Init] Initializing SDK module DataPipelines with config: DataPipelinesModuleConfig(cdpApiKey='[Redacted]', flushAt=20, flushInterval=30, flushPolicies=[], …
```
> chore: Update push setup logs

- messaginginapp/api/messaginginapp.api
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/InlineInAppMessageView.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/ModalInAppMessageView.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/InAppMessageViewController.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/InlineInAppMessageViewController.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/ModalInAppMessageViewController.kt
part of: [MBL-1091](https://linear.app/customerio/issue/MBL-1091/unified-action-handling-for-in-app-messages)
- Moved business logic out of in-app views into dedicated controller classes for better separation and testability.
- Views now only manage UI and forward interactions to their respective controllers.
- Introduced the following structure:
- `InAppMessageViewController`: Base controller for in-app message
- `ModalInAppMessageViewController`: Final controller for modal in-app messages
- `InlineInAppMessageViewController`: Final controller for inline in-app messages
- `ModalInAppMessageView`: Final view for modal (no common parent)
- `InlineInAppMessageView`: Final view for inline XML based usage (no common parent)
- #535
- #536 👈🏻
- #537
- Tests are not yet included to keep changes …
> chore: refactor in-app views to controller

- messaginginapp/api/messaginginapp.api
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistModalActivity.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/engine/EngineWebView.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/InlineInAppMessageView.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/ModalInAppMessageView.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/bridge/EngineWebViewDelegate.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/bridge/InAppHostViewDelegate.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/bridge/InAppMessageViewCallback.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/InAppMessageViewController.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/InlineInAppMessageViewController.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/ModalInAppMessageViewController.kt
part of: [MBL-1091](https://linear.app/customerio/issue/MBL-1091/unified-action-handling-for-in-app-messages)
- Added `EngineWebViewDelegate` to decouple controllers from `EngineWebView`
- Added `InAppHostViewDelegate` to decouple controllers from host in-app views
- Renamed `InAppMessageViewListener` to `InAppMessageViewCallback` (and similarly for child classes) for clearer naming
- #535
- #536
- #537 👈🏻
- Tests are not yet included to keep changes small and reviewable. Tests will be added once refactoring is complete.
- There are no intentional logic changes unless explicitly noted in comments. If you spot any, please flag them.
> chore: refactor in-app view calls to delegates

- messaginginapp/src/main/java/io/customer/messaginginapp/ui/bridge/InAppPlatformDelegate.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/InAppMessageViewController.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/InlineInAppMessageViewController.kt
part of: [MBL-1091](https://linear.app/customerio/issue/MBL-1091/unified-action-handling-for-in-app-messages)
- Simplified `openUrl` into single method with `useLaunchFlags` parameter for conditional behavior
- Removed unused methods from `InAppPlatformDelegate`
- Refactored `attachEngineWebView` using `also` block for cleaner syntax
- Removed `isEngineWebViewAttached` to simplify controller logic
- #535
- #536
- #537 
- #539 👈🏻
These are follow up improvements based on previous PRs in stack for same ticket.
> chore: in-app controller pr suggestions

- messagingpush/src/main/java/io/customer/messagingpush/CustomerIOPushNotificationHandler.kt
- messagingpush/src/main/java/io/customer/messagingpush/di/DiGraphMessagingPush.kt
- messagingpush/src/main/java/io/customer/messagingpush/logger/PushNotificationLogger.kt
- messagingpush/src/main/java/io/customer/messagingpush/processor/PushMessageProcessorImpl.kt
- messagingpush/src/test/java/io/customer/messagingpush/CustomerIOPushNotificationHandlerTest.kt
- messagingpush/src/test/java/io/customer/messagingpush/logger/PushNotificationLoggerTest.kt
- messagingpush/src/test/java/io/customer/messagingpush/processor/PushMessageProcessorTest.kt
Part of: [MBL-1075](https://linear.app/customerio/issue/MBL-1075/update-push-notifications-logging-for-android)
Closes: [MBL-1121](https://linear.app/customerio/issue/MBL-1121/update-push-notification-click-handling-logs)
This PR implements log definitions as defined in the log definitions repo https://github.com/customerio/mobile-log-definitions/pull/9
- Adds logs for push received handling, tracking delivery and opening
- Added unit test for the wrapper logger and call sites
- Logs after implementation are as follows
```
[CIO] D  [Init] Creating new instance of CustomerIO SDK version: 4.5.8...
[CIO] D  [Init] Initializing SDK module DataPipelines with config: DataPipelinesModuleConfig(cdpApiKey='[Redacted]', flushAt=20, flushInterval=30, flushPolicies=[], …
```
> chore: Update logs for handling push and tracking delivery and open events

- messaginginapp-compose/src/main/java/io/customer/messaginginapp/compose/InlineInAppMessageView.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ModuleMessagingInApp.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/state/InAppMessageReducer.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/state/InAppMessagingState.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/state/InAppMessagingStateExtensions.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/InlineInAppMessageView.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/InAppMessageViewController.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/InlineInAppMessageViewController.kt
- messaginginapp/src/main/java/io/customer/messaginginapp/ui/controller/ModalInAppMessageViewController.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/InAppMessagingStoreTest.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/state/InAppMessageReducerTest.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/ui/controller/InAppMessageViewControllerTest.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/ui/controller/InlineMessageViewControllerBehaviorTest.kt
closes: [MBL-1155](https://linear.app/customerio/issue/MBL-1155/fix-inline-message-view-not-dismissed-on-error)
- Updated `InAppMessageViewController` to dispatch the display event only once per message using flag
- In `InlineInAppMessageViewController`:
- Reset display event flag on dismiss to allow proper handling for the next message
- Called `onLoadingStarted` at start to improve loading UI experience
- In `ModalInAppMessageViewController`, ensured `EngineWebView` is updated only on first `routeLoaded`
- Updated `InAppMessageReducer` to dismiss inline messages on loading failure
- Moved inline message dismissal logic to an extension and extracted `InAppMessagingState` extensions to a dedicated file
- Moved min height setting from Compose view to base view for a consistent experience …
> chore: fix display event handling and error recovery for in-app messages

- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistModalActivity.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/gist/presentation/GistModalActivityTest.kt
part of: [MBL-940](https://linear.app/customerio/issue/MBL-940/android-crash-on-flutter-211-sdks)
When the app is restored from background by Android OS after being remove from memory while a modal message was displayed, it may crash on restoration if the SDK is not initialized in `Application` class. This occurs more frequently in wrapper SDKs where SDK initialization doesn't happen at app startup.
While not a long-term architectural fix, this reliably prevents crashes by:
- Finishing `GistModalActivity` early if the SDK is not initialized
- Lazily accessing SDK dependent properties in `GistModalActivity` to avoid triggering runtime exceptions
Tests have been added to enforce this behavior and prevent future regressions or accidental SDK access before initialization in …
> fix: finish modal message early if sdk is not initialized

- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/datapipelines/plugins/ContextPlugin.kt
- datapipelines/src/test/java/io/customer/datapipelines/plugins/ContextPluginBehaviorTest.kt
closes: [MBL-1198](https://linear.app/customerio/issue/MBL-1198/android-non-volatile-shared-property-in-contextplugin)
- Improved thread safety and testability for `ContextPlugin`:
- Marked `deviceToken` as `@Volatile` to ensure proper visibility across threads
- Extracted `ContextPluginEventProcessor` to isolate event processing logic and support test time behavior (e.g. timing assertions)
- Added tests to validate correct propagation and visibility of `deviceToken`, following the same path as in production
The PR is created as `chore` because the SDK currently works fine without this change, but this improves reliability and helps surface potential bugs earlier.
> chore: make device token thread safe

- core/src/main/kotlin/io/customer/sdk/communication/EventBus.kt
- core/src/test/java/io/customer/sdk/communication/EventBusTest.kt
Changes 
• Replace coroutine-per-event with hybrid channel-based approach to eliminate thread pool exhaustion risk
• Maintain 100-event replay buffer and all existing functionality while improving performance under load
• Add comprehensive test coverage for concurrent publishing, high-frequency scenarios, and replay buffer boundaries
Test plan
- All existing EventBus tests pass
- New concurrent publishing test validates no event loss/duplication under load
- High-frequency publishing test ensures 1000+ events process efficiently
- Replay buffer boundary test confirms 100-event limit works correctly
- No functional regressions in event ordering, subscription, or cleanup behavior
> chore: optimize EventBus performance under high-frequency publishing

- common-test/src/main/java/io/customer/commontest/util/ScopeProviderStub.kt
- core/api/core.api
- core/src/main/kotlin/io/customer/sdk/core/util/ScopeProvider.kt
- core/src/main/kotlin/io/customer/sdk/data/store/GlobalPreferenceStore.kt
- samples/java_layout/src/main/java/io/customer/android/sample/java_layout/sdk/CustomerIORepository.java
changes:
- Moved strict mode enabling before SDK startup rather App to avoid false positives of app
- We were storing `settings` on main thread, while this method doesn't need to be blocking nor it needs to be done in main thread. 
testing:
- Verified manually by running app and ensuring setting are being saved and running app without internet to ensure we are able to fetch loaded settings.
> chore: move setting storage to background

- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/sdk/DataPipelineInstance.kt
Closes: [MBL-1298](https://linear.app/customerio/issue/MBL-1298/tracking-api-alignment)
Deprecates overloaded methods in DataPipelineInstance that accept generic types or JsonObject parameters in favor of the Map<String, Any?> variants for better API consistency.
- Deprecated methods:
- `identify(userId: String, traits: Traits) (reified generic)`
- `identify(userId: String, traits: JsonObject)`
- `identify(userId: String, traits: Traits, serializationStrategy: SerializationStrategy<Traits>)`
- `track(name: String, properties: JsonObject)`
- `track(name: String, properties: T) (reified generic)`
- `track(name: String, properties: T, serializationStrategy: SerializationStrategy<T>)`
- `screen(title: String, properties: JsonObject)`
- `screen(title: String, properties: T) (reified generic)` …
> chore: Deprecate unnecessary non-Map overloads in DataPipelineInstance API

- datapipelines/api/datapipelines.api
- datapipelines/src/main/kotlin/io/customer/sdk/CustomerIO.kt
- datapipelines/src/main/kotlin/io/customer/sdk/DataPipelineInstance.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesCompatibilityTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/DataPipelinesInteractionTests.kt
- datapipelines/src/test/java/io/customer/datapipelines/DeviceAttributesTests.kt
- samples/kotlin_compose/src/main/java/io/customer/android/sample/kotlin_compose/ui/customTrack/CustomAttribute.kt
Closes: [MBL-1299](https://linear.app/customerio/issue/MBL-1299/device-and-user-enrichment-api-alignment)
Tweaks public API `deviceAttributes` to be `setDeviceAttributes` for clarify and consistency with other SDKs
> chore: Turn deviceAttributes into setDeviceAttributes

- messaginginapp/src/main/java/io/customer/messaginginapp/gist/presentation/GistModalActivity.kt
- messaginginapp/src/test/java/io/customer/messaginginapp/gist/presentation/GistModalActivityTest.kt
closes: [MBL-1347](https://linear.app/customerio/issue/MBL-1347/uninitializedpropertyaccessexception-on-gistmodalactivityfinish)
Fixes a crash (`UninitializedPropertyAccessException`) that occurs when `finish()` is called before `binding` property is initialized in `GistModalActivity`.
It looks like occurring when:
- `prepareActivity()` is triggered asynchronously in `onCreate()`
- User presses the back button before `initializeActivity()` completes
- `finish()` tries to access `binding.modalGistViewLayout`, which hasn't been initialized yet
```
at android.app.Activity.runOnUiThread(Activity.java:7762)
       at io.customer.messaginginapp.gist.presentation.GistModalActivity.finish(GistModalActivity.kt:162)
       at android.app.Activity.finishAfterTransition(Activity.java:7166)
       at …
```
> fix: prevent GistModalActivity crash on early back press

- buildSrc/src/main/kotlin/io.customer/android/Dependencies.kt
- buildSrc/src/main/kotlin/io.customer/android/Versions.kt
- buildSrc/src/main/kotlin/io.customer/android/apkscale/MeasureAndroidLibrarySizeTask.kt
- core/src/main/kotlin/io/customer/sdk/data/store/ApplicationStore.kt
- messagingpush/build.gradle
- messagingpush/src/main/java/io/customer/messagingpush/logger/PushNotificationLogger.kt
- messagingpush/src/main/java/io/customer/messagingpush/util/WorkManagerProvider.kt
- messagingpush/src/test/java/io/customer/messagingpush/logger/PushNotificationLoggerTest.kt
- samples/java_layout/build.gradle
- samples/kotlin_compose/build.gradle.kts
Close: [MBL-1350](https://linear.app/customerio/issue/MBL-1350/android-improve-push-metrics-background-deliverability)
Implementation is split across multiple PRs, here's a list to navigate:
- Adding `WorkManager` to push module -> **This PR**
- Move push messages delivery metrics to background -> https://github.com/customerio/customerio-android/pull/605
- Add tests for implementation -> https://github.com/customerio/customerio-android/pull/606
Android's power management features (Doze mode and App Standby) severely restrict background processing, preventing immediate delivery metric tracking when push notifications are received. Doze mode suspends network access and background services when devices are stationary and unplugged, while App Standby blocks background network access for …
> chore: Add WorkManager dependency and create safer provider

- messagingpush/src/main/java/io/customer/messagingpush/PushDeliveryTracker.kt
- messagingpush/src/main/java/io/customer/messagingpush/di/DiGraphMessagingPush.kt
- messagingpush/src/main/java/io/customer/messagingpush/network/HTTPClient.kt
- messagingpush/src/main/java/io/customer/messagingpush/processor/PushDeliveryMetricsBackgroundScheduler.kt
- messagingpush/src/main/java/io/customer/messagingpush/processor/PushMessageProcessorImpl.kt
Close: [MBL-1350](https://linear.app/customerio/issue/MBL-1350/android-improve-push-metrics-background-deliverability)
Implementation is split across multiple PRs, here's a list to navigate:
- Adding `WorkManager` to push module -> https://github.com/customerio/customerio-android/pull/604
- Move push messages delivery metrics to background -> **This PR**
- Add tests for implementation -> https://github.com/customerio/customerio-android/pull/606
Android's power management features (Doze mode and App Standby) severely restrict background processing, preventing immediate delivery metric tracking when push notifications are received. Doze mode suspends network access and background services when devices are stationary and unplugged, while App Standby blocks background network access for …
> chore: Send delivery receipts through WorkManager

- messagingpush/src/main/java/io/customer/messagingpush/PushDeliveryTracker.kt
- messagingpush/src/main/java/io/customer/messagingpush/di/DiGraphMessagingPush.kt
- messagingpush/src/main/java/io/customer/messagingpush/processor/PushMessageProcessorImpl.kt
- messagingpush/src/test/java/io/customer/messagingpush/PushDeliveryTrackingTest.kt
- messagingpush/src/test/java/io/customer/messagingpush/processor/PushDeliveryMetricsBackgroundSchedulerTest.kt
- messagingpush/src/test/java/io/customer/messagingpush/processor/PushDeliveryMetricsWorkerTest.kt
- messagingpush/src/test/java/io/customer/messagingpush/processor/PushMessageProcessorTest.kt
Close: [MBL-1350](https://linear.app/customerio/issue/MBL-1350/android-improve-push-metrics-background-deliverability)
Implementation is split across multiple PRs, here's a list to navigate:
- Adding `WorkManager` to push module -> https://github.com/customerio/customerio-android/pull/604
- Move push messages delivery metrics to background -> https://github.com/customerio/customerio-android/pull/605
- Add tests for implementation -> **This PR**
Android's power management features (Doze mode and App Standby) severely restrict background processing, preventing immediate delivery metric tracking when push notifications are received. Doze mode suspends network access and background services when devices are stationary and unplugged, while App Standby blocks background network access for …
> chore: Add tests for push delivery background scheduling
